Repository geist-org/geist-ui, pull requests merged in 2020-10, with the labels that each got.

#387 fix(page): fix page footer width
  components/page/__tests__/__snapshots__/child.test.tsx.snap
  components/page/page-footer.tsx
Labels: bug

#391 fix(grid): typo in grid.mdx
  pages/en-us/components/grid.mdx
Labels: type: documentation

#378 feat(table): add update row action to Table
  components/table/__tests__/index.test.tsx
  components/table/table-body.tsx
  components/table/table-cell.tsx
  components/table/table-context.ts
  components/table/table.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/table.mdx
  pages/zh-cn/components/table.mdx
Labels: type: feature

#398 docs(themes): fix example code of use-theme
  pages/en-us/guide/themes.mdx
  pages/zh-cn/guide/themes.mdx
Labels: type: documentation

#403 fix typo
  pages/en-us/guide/introduction.mdx
Labels: type: documentation

#406 docs: add short link for icons
  next.config.js
Labels: type: documentation

#396 feat(select): add clearable option to select multiple with test and english doc
  components/select/__tests__/multiple.test.tsx
  components/select/select-icon-clear.tsx
  components/select/select-multiple-value.tsx
  components/select/select.tsx
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: type: feature
