Repository geist-org/geist-ui, pull requests merged in 2020-03, with the labels that each got.

#2 feat(radio): add component
  components/index.ts
  components/radio/index.ts
  components/radio/radio-context.ts
  components/radio/radio-description.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/toast/use-toast.tsx
  components/utils/collections.ts
  components/utils/use-portal.ts
  lib/components/attributes/attributes-title.tsx
  lib/components/attributes/attributes.tsx
  now.json
  pages/_app.tsx
  pages/docs/components/avatar.mdx
  pages/docs/components/button-dropdown.mdx
  pages/docs/components/button.mdx
  pages/docs/components/capacity.mdx
  pages/docs/components/card.mdx
  pages/docs/components/checkbox.mdx
  pages/docs/components/code.mdx
  pages/docs/components/description.mdx
  pages/docs/components/display.mdx
  pages/docs/components/dot.mdx
  pages/docs/components/fieldset.mdx
  pages/docs/components/image.mdx
  pages/docs/components/input.mdx
  pages/docs/components/keyboard.mdx
  pages/docs/components/layout.mdx
  pages/docs/components/link.mdx
  pages/docs/components/modal.mdx
  pages/docs/components/note.mdx
  pages/docs/components/radio.mdx
  pages/docs/components/spacer.mdx
  pages/docs/components/spinner.mdx
  pages/docs/components/tag.mdx
  pages/docs/components/text.mdx
  pages/docs/components/toast.mdx
Labels: type: feature

#3 feat(link): display as a separate block
  components/link/link.tsx
  lib/components/index.ts
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/active-link.tsx
  lib/components/sidebar/side-item.tsx
  pages/docs/components/link.mdx
Labels: type: feature

#4 fix: fix heading for Spacer docs
  pages/docs/components/spacer.mdx
Labels: bug, type: documentation

#9 feat(select): add component
  components/index.ts
  components/select/index.ts
  components/select/select-context.ts
  components/select/select-icon.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/select/styles.ts
  components/shared/dropdown.tsx
  components/shared/portal.tsx
  components/utils/collections.ts
  components/utils/use-ssr.ts
  pages/docs/components/select.mdx
  pages/docs/getting-started/installation.mdx
Labels: type: feature

#10 docs: improve scrollbar on windows
  lib/components/sidebar/index.tsx
  pages/_app.tsx
Labels: type: documentation

#11 feat(tabs): add component
  components/button/button.tsx
  components/index.ts
  components/link/link.tsx
  components/tabs/index.ts
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  components/tabs/use-tabs.ts
  components/text/text.tsx
  lib/components/attributes/attributes-title.tsx
  lib/components/playground/title.tsx
  pages/docs/components/tabs.mdx
  pages/docs/getting-started/introduction.mdx
  pages/docs/getting-started/server-render.mdx
Labels: type: feature

#12 docs: improve the layout of mobile screen
  lib/components/attributes/attributes.tsx
  lib/components/controls.tsx
  lib/components/icons/toggle.tsx
  lib/components/layout.tsx
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/side-item.tsx
  lib/components/sidebar/tabbar-mobile.tsx
  pages/_app.tsx
  pages/docs/index.js
Labels: type: documentation

#13 Add progress component
  components/capacity/capacity.tsx
  components/index.ts
  components/progress/index.ts
  components/progress/progress.tsx
  components/spacer/spacer.tsx
  components/utils/calculations.ts
  pages/docs/components/progress.mdx
  pages/docs/components/spacer.mdx
Labels: type: feature

#14 Add hooks and remove some duplicate functions
  components/button-dropdown/button-dropdown.tsx
  components/checkbox/checkbox-group.tsx
  components/checkbox/checkbox.tsx
  components/fieldset/fieldset-group.tsx
  components/fieldset/fieldset.tsx
  components/radio/radio.tsx
  components/select/select-context.ts
  components/select/select-dropdown.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/dropdown.tsx
  components/spacer/spacer.tsx
  components/styles/theme-provider/theme-provider.tsx
  components/tabs/tabs.tsx
  components/utils/use-click-anywhere.ts
  components/utils/use-click-away.ts
  components/utils/use-portal.ts
  components/utils/use-resize.ts
  components/utils/use-warning.ts
Labels: bug, type: chore, type: documentation

#15 feat(file-tree): add component
  components/file-tree/index.ts
  components/file-tree/tree-context.ts
  components/file-tree/tree-file-icon.tsx
  components/file-tree/tree-file.tsx
  components/file-tree/tree-folder-icon.tsx
  components/file-tree/tree-folder.tsx
  components/file-tree/tree-help.ts
  components/file-tree/tree-indents.tsx
  components/file-tree/tree-status-icon.tsx
  components/file-tree/tree.tsx
  components/index.ts
  components/shared/expand.tsx
  components/styles/css-baseline/css-baseline.tsx
  components/utils/collections.ts
  pages/docs/components/file-tree.mdx
Labels: type: feature

#16 docs: add example project for create-react-app
  pages/docs/getting-started/installation.mdx
Labels: type: documentation

#17 docs: fix typo
  pages/docs/getting-started/installation.mdx
Labels: type: documentation

#20 Improve styles & add body scroll hooks
  components/modal/modal.tsx
  components/toast/toast-item.tsx
  components/utils/use-body-scroll.ts
  lib/components/layout.tsx
  lib/components/playground/index.tsx
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/side-item.tsx
Labels: type: documentation, type: feature

#24 fix(button-dropdown): fix button text vertical alignment on firefox
  components/button-dropdown/button-dropdown-item.tsx
  components/button-dropdown/button-dropdown.tsx
  components/button-dropdown/index.ts
Labels: bug

#25 docs: remove text-transform on active link
  lib/components/sidebar/side-item.tsx
Labels: type: documentation

#26 fix(input): fix value update from controlled component
  components/input/input.tsx
Labels: bug

#27 feat: add badge component
  components/badge/badge.tsx
  components/badge/index.ts
  components/index.ts
  components/styles/css-baseline/css-baseline.tsx
  pages/docs/components/badge.mdx
Labels: type: feature

#29 feat(input): add custom width to fit more layouts
  components/input/input-icon-clear.tsx
  components/input/input.tsx
  pages/docs/components/input.mdx
Labels: type: feature

#28 fix(avatar): Fix HTML Attributes
  components/avatar/avatar.tsx
Labels: bug

#30 feat(auto complete): add component
  components/auto-complete/auto-complete-context.ts
  components/auto-complete/auto-complete-dropdown.tsx
  components/auto-complete/auto-complete-empty.tsx
  components/auto-complete/auto-complete-item.tsx
  components/auto-complete/auto-complete-searching.tsx
  components/auto-complete/auto-complete.tsx
  components/auto-complete/index.ts
  components/button/button.loading.tsx
  components/index.ts
  components/input/input-icon-clear.tsx
  components/input/input-icon.tsx
  components/input/input.tsx
  pages/docs/components/auto-complete.mdx
Labels: type: feature

#31 feat(collapse): add component
  components/collapse/collapse-context.ts
  components/collapse/collapse-group.tsx
  components/collapse/collapse-icon.tsx
  components/collapse/collapse.tsx
  components/collapse/index.ts
  components/index.ts
  components/utils/collections.ts
  pages/docs/components/collapse.mdx
Labels: type: feature

#32 feat(loading): add component
  components/auto-complete/auto-complete.tsx
  components/button-dropdown/button-dropdown-item.tsx
  components/button/button.loading.tsx
  components/button/button.tsx
  components/index.ts
  components/input/input-icon.tsx
  components/loading/index.ts
  components/loading/loading.tsx
  pages/docs/components/loading.mdx
  pages/docs/components/spinner.mdx
Labels: type: feature

#33 fix(avatar): fix union types for different elements
  components/avatar/avatar.tsx
Labels: bug

#35 fix(theme): export types of theme
  components/index.ts
Labels: bug

#36 feat(textarea): add component
  components/index.ts
  components/input/index.ts
  components/input/input.tsx
  components/textarea/index.ts
  components/textarea/textarea.tsx
  pages/docs/components/textarea.mdx
Labels: type: feature

#37 fix: override types
  components/auto-complete/auto-complete.tsx
  components/avatar/avatar.tsx
  components/badge/badge.tsx
  components/button-dropdown/button-dropdown-item.tsx
  components/button-dropdown/button-dropdown.tsx
  components/button/button.tsx
  components/capacity/capacity.tsx
  components/card/card.tsx
  components/checkbox/checkbox-group.tsx
  components/checkbox/checkbox.tsx
  components/code/code.tsx
  components/col/col.tsx
  components/collapse/collapse-group.tsx
  components/collapse/collapse.tsx
  components/description/description.tsx
  components/display/display.tsx
  components/dot/dot.tsx
  components/fieldset/fieldset-footer-actions.tsx
  components/fieldset/fieldset-footer-status.tsx
  components/fieldset/fieldset-footer.tsx
  components/fieldset/fieldset-group.tsx
  components/fieldset/fieldset-subtitle.tsx
  components/fieldset/fieldset-title.tsx
  components/fieldset/fieldset.tsx
  components/file-tree/tree-file.tsx
  components/file-tree/tree-folder.tsx
  components/file-tree/tree.tsx
  components/image/image.tsx
  components/input/input.tsx
  components/keyboard/keyboard.tsx
  components/link/link.tsx
  components/loading/loading.tsx
  components/modal/modal-action.tsx
  components/modal/modal-content.tsx
  components/modal/modal-subtitle.tsx
  components/modal/modal-title.tsx
  components/modal/modal.tsx
  components/note/note.tsx
  components/progress/progress.tsx
  components/radio/radio-description.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/row/row.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/spacer/spacer.tsx
  components/spinner/spinner.tsx
  components/tabs/tabs.tsx
  components/tag/tag.tsx
  components/text/child.tsx
  components/text/text.tsx
  components/textarea/textarea.tsx
Labels: bug

#40 docs: add color cards
  components/styles/themes/dark.ts
  components/styles/themes/default.ts
  components/styles/themes/index.ts
  components/toast/use-toast.tsx
  lib/components/displays/colors-data.ts
  lib/components/displays/colors.tsx
  lib/components/playground/index.tsx
  package.json
  pages/docs/customization/colors.mdx
  pages/docs/customization/themes.mdx
  yarn.lock
Labels: type: documentation, type: feature

#41 docs: fix switch themes code
  pages/docs/customization/themes.mdx
Labels: type: documentation
