Repository geist-org/geist-ui, pull requests merged in 2020-05, with the labels that each got.

#160 test(shared): add testcases for shared components
  components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
  components/shared/__tests__/__snapshots__/dropdown.test.tsx.snap
  components/shared/__tests__/__snapshots__/transition.test.tsx.snap
  components/shared/__tests__/backdrop.test.tsx
  components/shared/__tests__/dropdown.test.tsx
  components/shared/__tests__/transition.test.tsx
  components/shared/dropdown.tsx
Labels: type: test

#164 chore(gh): update contributing guide
  .github/CONTRIBUTING.md
Labels: type: chore

#161 test: add test cases for exported utility functions
  components/index.ts
  components/utils-shared/__tests__/body-scroll.test.tsx
  components/utils-shared/__tests__/click-away.test.tsx
  components/utils-shared/__tests__/clipboard.test.tsx
  components/utils-shared/__tests__/current-state.test.tsx
  components/utils-shared/index.ts
  components/utils-shared/use-body-scroll.ts
  components/utils-shared/use-click-away.ts
  components/utils-shared/use-clipboard.ts
  components/utils-shared/use-current-state.ts
  components/utils/index.ts
  components/utils/use-body-scroll.ts
  components/utils/use-click-away.ts
  components/utils/use-clipboard.ts
  components/utils/use-current-state.ts
  package.json
  yarn.lock
Labels: type: test

#166 docs(utils): add docs
  components/utils-shared/__tests__/current-state.test.tsx
  components/utils-shared/use-current-state.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/use-body-scroll.mdx
  pages/en-us/components/use-click-away.mdx
  pages/en-us/components/use-clipboard.mdx
  pages/en-us/components/use-current-state.mdx
  pages/zh-cn/components/use-body-scroll.mdx
  pages/zh-cn/components/use-click-away.mdx
  pages/zh-cn/components/use-clipboard.mdx
  pages/zh-cn/components/use-current-state.mdx
  scripts/collect-meta.js
Labels: type: documentation

#162 docs: add icons documents
  components/card/__tests__/__snapshots__/footer.test.tsx.snap
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/card/card-content.tsx
  components/card/card.tsx
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/modal-content.tsx
  lib/components/displays/icons-cell.tsx
  lib/components/displays/icons.tsx
  lib/components/icons/logo.tsx
  lib/data/metadata-en-us.json
  pages/en-us/components/icons.mdx
Labels: type: documentation

#167 fix(dropdown): modify z-index of dropdown
  components/shared/dropdown.tsx
  lib/components/menu/menu-sticker.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/index.js
  pages/en-us/components/spacer.mdx
  pages/en-us/components/text.mdx
  pages/zh-cn/components/index.js
  pages/zh-cn/components/spacer.mdx
  pages/zh-cn/components/text.mdx
Labels: bug

#168 docs: optimize time of page load
  lib/components/layout.tsx
  lib/components/menu/index.tsx
  lib/components/playground/index.ts
  lib/components/playground/playground.tsx
  pages/_document.tsx
Labels: type: documentation

#169 docs(icons): add icons for chinese
  lib/components/displays/icons.tsx
  lib/data/metadata-zh-cn.json
  package.json
  pages/zh-cn/components/button.mdx
  pages/zh-cn/components/icons.mdx
Labels: type: documentation

#170 fix(playground): fix arrow icon does not work correctly on webkit
  lib/components/playground/editor.tsx
  lib/components/playground/playground.tsx
Labels: type: documentation

#174 feat(page): add component
  components/index.ts
  components/page/__tests__/__snapshots__/child.test.tsx.snap
  components/page/__tests__/__snapshots__/index.test.tsx.snap
  components/page/__tests__/child.test.tsx
  components/page/__tests__/index.test.tsx
  components/page/index.ts
  components/page/page-content.tsx
  components/page/page-footer.tsx
  components/page/page-header.tsx
  components/page/page.tsx
  components/page/styles.ts
  lib/components/displays/mock-page.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/page.mdx
  pages/zh-cn/components/page.mdx
Labels: type: feature

#179 feat(button): support to display icons in button
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/__tests__/icon.test.tsx
  components/button/__tests__/index.test.tsx
  components/button/button-icon.tsx
  components/button/button.tsx
  components/button/index.ts
  components/button/styles.ts
  components/toast/__tests__/__snapshots__/index.test.tsx.snap
  components/toast/__tests__/index.test.tsx
  pages/en-us/components/button.mdx
  pages/zh-cn/components/button.mdx
Labels: type: feature

#180 feat(link): hide icon of link component by default
  components/image/__tests__/__snapshots__/browser.test.tsx.snap
  components/image/image-browser.tsx
  components/link/__tests__/__snapshots__/index.test.tsx.snap
  components/link/__tests__/index.test.tsx
  components/link/icon.tsx
  components/link/link.tsx
  components/user/user-link.tsx
  lib/components/anchor/index.tsx
  lib/components/attributes/contributors.tsx
  pages/en-us/components/badge.mdx
  pages/en-us/components/card.mdx
  pages/en-us/components/code.mdx
  pages/en-us/components/link.mdx
  pages/en-us/components/modal.mdx
  pages/en-us/components/popover.mdx
  pages/en-us/components/tooltip.mdx
  pages/en-us/components/use-body-scroll.mdx
  pages/en-us/components/use-click-away.mdx
  pages/en-us/components/use-clipboard.mdx
  pages/en-us/components/use-current-state.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/introduction.mdx
  pages/en-us/guide/server-render.mdx
  pages/en-us/guide/themes.mdx
  pages/zh-cn/components/badge.mdx
  pages/zh-cn/components/card.mdx
  pages/zh-cn/components/code.mdx
  pages/zh-cn/components/link.mdx
  pages/zh-cn/components/modal.mdx
  pages/zh-cn/components/popover.mdx
  pages/zh-cn/components/tabs.mdx
  pages/zh-cn/components/tooltip.mdx
  pages/zh-cn/components/use-body-scroll.mdx
  pages/zh-cn/components/use-click-away.mdx
  pages/zh-cn/components/use-clipboard.mdx
  pages/zh-cn/components/use-current-state.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/guide/introduction.mdx
  pages/zh-cn/guide/server-render.mdx
  pages/zh-cn/guide/themes.mdx
Labels: type: feature

#183 build: split output by module
  rollup.config.js
Labels: type: chore

#184 chore(pkg): release v1.1.0
  .github/workflows/publish.yml
  package.json
Labels: type: chore

#185 fix: fixed typo
  pages/en-us/components/image.mdx
Labels: type: documentation

#188 feat(modal): custom width and className
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/__tests__/index.test.tsx
  components/modal/modal-wrapper.tsx
  components/modal/modal.tsx
  package.json
  pages/en-us/components/modal.mdx
  pages/zh-cn/components/modal.mdx
Labels: type: feature

#192 feat: add Grid component
  .jest.config.js
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/__tests__/index.test.tsx
  components/grid/basic-item.tsx
  components/grid/grid-container.tsx
  components/grid/grid-types.ts
  components/grid/grid.tsx
  components/grid/index.ts
  components/index.ts
  components/page/__tests__/__snapshots__/child.test.tsx.snap
  components/page/__tests__/__snapshots__/index.test.tsx.snap
  components/styles/themes/dark.ts
  components/styles/themes/default.ts
  components/styles/themes/index.ts
  components/styles/themes/shared.ts
  lib/components/playground/playground.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/grid.mdx
  pages/zh-cn/components/grid.mdx
Labels: type: feature

#194 fix: type of useInput
  components/input/use-input.ts
Labels: bug

#196 fix: fix backdrop layer prevent default behavior
  components/shared/backdrop.tsx
Labels: bug

#197 feat(button-group): add component
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button-group/__tests__/index.test.tsx
  components/button-group/button-group-context.ts
  components/button-group/button-group.tsx
  components/button-group/index.ts
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/button.tsx
  components/button/utils.tsx
  components/index.ts
  components/toast/__tests__/__snapshots__/index.test.tsx.snap
  components/toast/__tests__/index.test.tsx
  components/toast/toast-container.tsx
  components/toast/toast-item.tsx
  components/toast/use-toast.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/button-group.mdx
  pages/zh-cn/components/button-group.mdx
Labels: type: feature

#198 chore: upgrade deps
  .eslintignore
  next.config.js
  package.json
  yarn.lock
Labels: type: chore

#199 fix(grid): fix side effects of global styles
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/grid-container.tsx
  components/grid/grid.tsx
  tests/__mocks__/styled-jsx/css.js
Labels: bug

#200 feat: add hooks for media query
  components/utils-shared/__tests__/media-query.test.tsx
  components/utils-shared/index.ts
  components/utils-shared/use-media-query.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  package.json
  pages/en-us/components/use-media-query.mdx
  pages/zh-cn/components/use-media-query.mdx
  yarn.lock
Labels: type: feature

#202 fix: fix form events ignored
  components/button/__tests__/__snapshots__/index.test.tsx.snap
  components/button/button.tsx
  pages/en-us/components/button.mdx
  pages/zh-cn/components/button.mdx
Labels: bug

#204 fix(tooltip): fix autowrap errors for elements wrapped by tooltip
  components/popover/__tests__/__snapshots__/index.test.tsx.snap
  components/tooltip/tooltip.tsx
Labels: bug

#205 fix(page): fix page width too large at md breakpoint
  components/page/__tests__/__snapshots__/child.test.tsx.snap
  components/page/__tests__/__snapshots__/index.test.tsx.snap
  components/page/page.tsx
  lib/components/displays/mock-page.tsx
Labels: bug

#207 build: supprot esm bundle
  .eslintignore
  .gitignore
  .nowignore
  .prettierignore
  components/css-baseline-deprecated/index.ts
  components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
  components/css-baseline/__tests__/baseline.test.tsx
  components/css-baseline/css-baseline.tsx
  components/css-baseline/index.ts
  components/index.ts
  components/page/__tests__/index.test.tsx
  components/snippet/snippet.tsx
  components/styles/__tests__/theme-provider.test.tsx
  components/tooltip/__test__/index.test.tsx
  components/tree/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/__tests__/index.test.tsx
  components/tree/index.ts
  components/tree/tree-context.ts
  components/tree/tree-file-icon.tsx
  components/tree/tree-file.tsx
  components/tree/tree-folder-icon.tsx
  components/tree/tree-folder.tsx
  components/tree/tree-help.ts
  components/tree/tree-indents.tsx
  components/tree/tree-status-icon.tsx
  components/tree/tree.tsx
  components/use-body-scroll/__tests__/body-scroll.test.tsx
  components/use-body-scroll/index.ts
  components/use-body-scroll/use-body-scroll.ts
  components/use-click-away/__tests__/click-away.test.tsx
  components/use-click-away/index.ts
  components/use-click-away/use-click-away.ts
  components/use-clipboard/__tests__/clipboard.test.tsx
  components/use-clipboard/index.ts
  components/use-clipboard/use-clipboard.ts
  components/use-current-state/__tests__/current-state.test.tsx
  components/use-current-state/index.ts
  components/use-current-state/use-current-state.ts
  components/use-media-query/__tests__/media-query.test.tsx
  components/use-media-query/index.ts
  components/use-media-query/use-media-query.ts
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  components/use-toasts/__tests__/index.test.tsx
  components/use-toasts/index.ts
  components/use-toasts/toast-container.tsx
  components/use-toasts/toast-item.tsx
  components/use-toasts/use-toast.tsx
  components/utils-shared-deprecated/index.ts
  components/utils-shared/index.ts
  components/utils/use-body-scroll.ts
  components/utils/use-click-away.ts
  components/utils/use-clipboard.ts
  components/utils/use-current-state.ts
  components/utils/use-zeit-ui-context.ts
  components/zeit-provider-deprecated/index.ts
  components/zeit-provider/index.ts
  components/zeit-provider/zeit-provider.tsx
  package.json
  scripts/babel.config.js
  yarn.lock
Labels: type: feature

#208 chore: remove deprecated props
  components/code/__tests__/__snapshots__/index.test.tsx.snap
  components/code/__tests__/index.test.tsx
  components/code/code.tsx
Labels: type: chore

#209 chore: add example for tree-shaking
  examples/tree-shaking-create-react-app/README.md
  examples/tree-shaking-create-react-app/config-overrides.js
  examples/tree-shaking-create-react-app/package.json
  examples/tree-shaking-create-react-app/public/esm-1.png
  examples/tree-shaking-create-react-app/public/esm-2.png
  examples/tree-shaking-create-react-app/public/index.html
  examples/tree-shaking-create-react-app/src/home.jsx
  examples/tree-shaking-create-react-app/src/index.jsx
  examples/tree-shaking-create-react-app/yarn.lock
  examples/tree-shaking-webpack/.babelrc
  examples/tree-shaking-webpack/README.md
  examples/tree-shaking-webpack/esm-1.png
  examples/tree-shaking-webpack/esm-2.png
  examples/tree-shaking-webpack/package.json
  examples/tree-shaking-webpack/src/index.html
  examples/tree-shaking-webpack/src/index.js
  examples/tree-shaking-webpack/webpack.config.js
  examples/tree-shaking-webpack/yarn.lock
Labels: type: chore

#210 chore: remove unnecessary warnings of deprecated
  README.md
  components/css-baseline-deprecated/index.ts
  components/index.ts
  components/utils-shared-deprecated/index.ts
  components/zeit-provider-deprecated/index.ts
  lib/components/playground/editor.tsx
  pages/_app.tsx
  pages/en-us/components/grid.mdx
  pages/en-us/components/use-body-scroll.mdx
  pages/en-us/components/use-click-away.mdx
  pages/en-us/components/use-clipboard.mdx
  pages/en-us/components/use-current-state.mdx
  pages/en-us/components/use-media-query.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/server-render.mdx
  pages/en-us/guide/themes.mdx
  pages/zh-cn/components/grid.mdx
  pages/zh-cn/components/use-body-scroll.mdx
  pages/zh-cn/components/use-click-away.mdx
  pages/zh-cn/components/use-clipboard.mdx
  pages/zh-cn/components/use-current-state.mdx
  pages/zh-cn/components/use-media-query.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/guide/server-render.mdx
  pages/zh-cn/guide/themes.mdx
Labels: type: chore

#211 fix(input): fix icon event is cached incorrectly
  components/input/input.tsx
Labels: bug

#214 fix(input): fix default width of Input cannot shrink under flex
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/__snapshots__/password.test.tsx.snap
  components/input/input.tsx
  pages/en-us/components/input.mdx
  pages/zh-cn/components/input.mdx
Labels: bug

#217 docs: fix out of date API in the server-render example
  pages/en-us/guide/server-render.mdx
  pages/zh-cn/guide/server-render.mdx
Labels: type: documentation

#220 docs: add loading component when loading playgound dynamically
  lib/components/playground/dynamic-live.tsx
  lib/components/playground/index.ts
  lib/components/playground/playground.tsx
  next.config.js
  package.json
  yarn.lock
Labels: type: documentation

#221 feat(button): forward the ref of the original element
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/index.test.tsx
  components/button/button.tsx
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  pages/en-us/components/button.mdx
  pages/en-us/components/input.mdx
  pages/en-us/components/link.mdx
  pages/zh-cn/components/button.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/link.mdx
Labels: type: feature

#227 feat(user): provide a prop for alt text
  components/user/__tests__/index.test.tsx
  components/user/user.tsx
  pages/en-us/components/user.mdx
  pages/zh-cn/components/user.mdx
Labels: type: feature

#230 feat(radio): add support of different sizes
  components/radio/__tests__/__snapshots__/group.test.tsx.snap
  components/radio/__tests__/__snapshots__/index.test.tsx.snap
  components/radio/__tests__/group.test.tsx
  components/radio/__tests__/index.test.tsx
  components/radio/radio-context.ts
  components/radio/radio-description.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  pages/en-us/components/radio.mdx
  pages/zh-cn/components/radio.mdx
Labels: type: feature

#231 feat(checkbox): add support of different sizes
  components/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  components/checkbox/__tests__/group.test.tsx
  components/checkbox/__tests__/index.test.tsx
  components/checkbox/checkbox-group.tsx
  components/checkbox/checkbox.icon.tsx
  components/checkbox/checkbox.tsx
  pages/en-us/components/checkbox.mdx
  pages/zh-cn/components/checkbox.mdx
Labels: type: feature

#232 refactor(radio): use CSS variable instead of Context broadcast size
  components/radio/__tests__/__snapshots__/group.test.tsx.snap
  components/radio/radio-context.ts
  components/radio/radio-group.tsx
  components/radio/radio.tsx
Labels: type: refactor

#233 feat(select): handle multiple selections
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/__tests__/index.test.tsx
  components/select/__tests__/multiple.test.tsx
  components/select/select-context.ts
  components/select/select-multiple-value.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/dropdown.tsx
  components/use-current-state/__tests__/current-state.test.tsx
  components/use-current-state/use-current-state.ts
  components/utils/collections.ts
  components/utils/use-dom-observer.ts
  pages/en-us/components/select.mdx
  pages/en-us/components/use-current-state.mdx
  pages/zh-cn/components/select.mdx
  pages/zh-cn/components/use-current-state.mdx
Labels: type: feature

#234 chore(examples): add create-next-app example
  examples/create-next-app/.gitignore
  examples/create-next-app/README.md
  examples/create-next-app/package.json
  examples/create-next-app/pages/_app.js
  examples/create-next-app/pages/_document.js
  examples/create-next-app/pages/index.js
  examples/create-next-app/public/favicon.ico
  examples/create-next-app/public/vercel.svg
  examples/create-next-app/yarn.lock
Labels: type: chore

#236 fix(modal): set body hidden false on close modal
  components/modal/modal.tsx
  pages/en-us/components/modal.mdx
Labels: bug

#238 docs: optimize document site
  lib/components/customization/codes.tsx
  lib/components/header.tsx
  lib/components/layout.tsx
  pages/en-us/customization/index.tsx
  pages/en-us/guide/colors.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/introduction.mdx
  pages/zh-cn/customization/index.tsx
  pages/zh-cn/guide/colors.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/guide/introduction.mdx
Labels: type: documentation

#241 feat(select): disable dropdown follow parent width
  components/select/select-dropdown.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/dropdown.tsx
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: type: feature

#242 fix(radio): fix style imbalance caused by decimal width
  components/radio/__tests__/__snapshots__/group.test.tsx.snap
  components/radio/__tests__/__snapshots__/index.test.tsx.snap
  components/radio/radio-group.tsx
Labels: bug

#244 chore: release v1.6.0
  components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
  components/auto-complete/auto-complete-dropdown.tsx
  components/auto-complete/auto-complete-item.tsx
  components/auto-complete/auto-complete.tsx
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/index.test.tsx
  components/button/button.tsx
  components/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  components/checkbox/__tests__/group.test.tsx
  components/checkbox/__tests__/index.test.tsx
  components/checkbox/checkbox-group.tsx
  components/checkbox/checkbox.icon.tsx
  components/checkbox/checkbox.tsx
  components/radio/__tests__/__snapshots__/group.test.tsx.snap
  components/radio/__tests__/__snapshots__/index.test.tsx.snap
  components/radio/__tests__/group.test.tsx
  components/radio/__tests__/index.test.tsx
  components/radio/radio-context.ts
  components/radio/radio-description.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/__tests__/index.test.tsx
  components/select/__tests__/multiple.test.tsx
  components/select/select-context.ts
  components/select/select-dropdown.tsx
  components/select/select-multiple-value.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/dropdown.tsx
  components/use-current-state/__tests__/current-state.test.tsx
  components/use-current-state/use-current-state.ts
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  components/user/__tests__/index.test.tsx
  components/user/user.tsx
  components/utils/collections.ts
  components/utils/use-dom-observer.ts
  package.json
  pages/en-us/components/auto-complete.mdx
  pages/en-us/components/button.mdx
  pages/en-us/components/checkbox.mdx
  pages/en-us/components/input.mdx
  pages/en-us/components/link.mdx
  pages/en-us/components/radio.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/use-current-state.mdx
  pages/en-us/components/user.mdx
  pages/zh-cn/components/auto-complete.mdx
  pages/zh-cn/components/button.mdx
  pages/zh-cn/components/checkbox.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/link.mdx
  pages/zh-cn/components/radio.mdx
  pages/zh-cn/components/select.mdx
  pages/zh-cn/components/use-current-state.mdx
  pages/zh-cn/components/user.mdx
Labels: type: chore

#248 fix: fix placeholder does not show ellipsis
  components/auto-complete/auto-complete-item.tsx
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/__tests__/multiple.test.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/__tests__/__snapshots__/ellipsis.test.tsx.snap
  components/shared/__tests__/ellipsis.test.tsx
  components/shared/ellipsis.tsx
Labels: bug

#252 fix: fix loading is not display under auto width
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/button-loading.tsx
  components/button/button.tsx
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  pages/en-us/components/button.mdx
  pages/zh-cn/components/button.mdx
Labels: bug

#254 fix(controls): fix option content not center vertically
  lib/components/controls.tsx
Labels: type: documentation
