Repository geist-org/geist-ui, pull requests merged in 2020-07, with the labels that each got.

#305 fix(auto-complete): fix the height of custom options
  components/auto-complete/auto-complete-item.tsx
  components/auto-complete/auto-complete.tsx
  pages/en-us/components/auto-complete.mdx
  pages/zh-cn/components/auto-complete.mdx
Labels: bug

#307 fix(popover): fix the undefined classname
  components/popover/popover-item.tsx
  components/popover/popover.tsx
Labels: bug

#308 fix(tabs): add role="button" to tab for a11y
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs.tsx
Labels: bug

#318 chore(gh): add help support template
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: chore

#320 fix: typo
  pages/en-us/guide/server-render.mdx
Labels: type: documentation

#325 fix(snippet): remove space when the symbol is empty
  components/button/button.tsx
  components/image/__tests__/browser.test.tsx
  components/snippet/__tests__/__snapshots__/index.test.tsx.snap
  components/snippet/__tests__/index.test.tsx
  components/snippet/snippet.tsx
Labels: bug

#329 docs: add example for custom colors
  lib/components/playground/playground.tsx
  lib/components/playground/title.tsx
  pages/en-us/components/badge.mdx
  pages/zh-cn/components/badge.mdx
Labels: type: documentation

#334 feat(tabs): sync the label and set value to required
  components/tabs/__tests__/index.test.tsx
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  pages/en-us/components/tabs.mdx
  pages/zh-cn/components/tabs.mdx
Labels: type: feature

#336 fix(input): always synchronize external value and ignore changes
  components/input/input.tsx
  pages/en-us/components/input.mdx
  pages/zh-cn/components/input.mdx
Labels: bug

#344 feat(dropdown): allow dropdown to set the specified container
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/modal-content.tsx
  components/select/select-dropdown.tsx
  components/select/select.tsx
  components/shared/__tests__/dropdown.test.tsx
  components/shared/dropdown.tsx
  components/utils/use-portal.ts
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: type: feature

#348 style(description): fix title font-weight
  components/description/description.tsx
Labels: type: styles

#346 docs(link): fix duplicate examples
  pages/en-us/components/link.mdx
  pages/zh-cn/components/link.mdx
Labels: type: documentation

#345 style(popover-item): the whole item should be clickable when using with link
  components/popover/popover-item.tsx
Labels: type: styles

#351 fix(modal): fix type of Modal.Action
  components/modal/modal-action.tsx
Labels: bug
