Repository geist-org/geist-ui, pull requests merged in 2020-04, with the labels that each got.

#44 feat(toggle): add components
  components/checkbox/checkbox.tsx
  components/index.ts
  components/styles/css-baseline/css-baseline.tsx
  components/toggle/index.ts
  components/toggle/toggle.tsx
  pages/docs/components/checkbox.mdx
  pages/docs/components/toggle.mdx
Labels: type: feature

#45 feat(input): allow user to customize label content
  components/input/input-block-label.tsx
  components/input/input.tsx
  pages/docs/components/input.mdx
Labels: type: feature

#46 fix: fix alignment issues caused by line-height on safari
  components/dot/dot.tsx
  components/input/input.tsx
Labels: bug

#48 feat(link): forward ref for next/link compatibility
  components/link/link.tsx
  pages/docs/components/link.mdx
Labels: type: feature

#49 feat(snippet): add component
  components/code/code.tsx
  components/index.ts
  components/snippet/index.ts
  components/snippet/snippet-icon.tsx
  components/snippet/snippet.tsx
  components/snippet/styles.ts
  components/styles/css-baseline/css-baseline.tsx
  components/utils/prop-types.ts
  components/utils/use-clipboard.ts
  components/utils/use-portal.ts
  lib/components/displays/colors.tsx
  lib/components/playground/index.tsx
  package.json
  pages/docs/components/code.mdx
  pages/docs/components/display.mdx
  pages/docs/components/snippet.mdx
  pages/docs/getting-started/installation.mdx
  yarn.lock
Labels: type: feature

#50 docs: add description information for all components
  components/link/link.tsx
  lib/components/anchor/anchor-icon.tsx
  lib/components/anchor/index.tsx
  lib/components/attributes/attributes-title.tsx
  lib/components/attributes/attributes.tsx
  lib/components/playground/title.tsx
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/side-item.tsx
  pages/docs/components/auto-complete.mdx
  pages/docs/components/avatar.mdx
  pages/docs/components/badge.mdx
  pages/docs/components/button-dropdown.mdx
  pages/docs/components/button.mdx
  pages/docs/components/capacity.mdx
  pages/docs/components/code.mdx
  pages/docs/components/collapse.mdx
  pages/docs/components/description.mdx
  pages/docs/components/display.mdx
  pages/docs/components/dot.mdx
  pages/docs/components/fieldset.mdx
  pages/docs/components/input.mdx
  pages/docs/components/link.mdx
  pages/docs/components/loading.mdx
  pages/docs/components/modal.mdx
  pages/docs/components/note.mdx
  pages/docs/components/progress.mdx
  pages/docs/components/radio.mdx
  pages/docs/components/select.mdx
  pages/docs/components/snippet.mdx
  pages/docs/components/spinner.mdx
  pages/docs/components/table.mdx
  pages/docs/components/tabs.mdx
  pages/docs/components/textarea.mdx
  pages/docs/components/toast.mdx
  pages/docs/components/toggle.mdx
Labels: type: documentation

#51 docs: restore the scroll bar of the menu when hash changed
  lib/components/config-context.ts
  lib/components/config-provider.tsx
  lib/components/controls.tsx
  lib/components/sidebar/active-link.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/side-item.tsx
  lib/states/config-context.ts
  lib/states/use-config.ts
  package.json
  yarn.lock
Labels: type: documentation

#53 fix(badge): fix the foregroud color is covered in dark mode
  components/badge/badge.tsx
Labels: bug

#56 fix(types): fix ignore native types when export types manually
  components/auto-complete/auto-complete.tsx
  components/button-dropdown/button-dropdown.tsx
  components/checkbox/checkbox.tsx
  components/collapse/collapse.tsx
  components/fieldset/fieldset-footer.tsx
  components/fieldset/fieldset.tsx
  components/file-tree/tree.tsx
  components/input/input.tsx
  components/modal/modal.tsx
  components/radio/radio.tsx
  components/select/select.tsx
  components/table/table.tsx
  components/tabs/tabs.tsx
Labels: bug

#57 docs(themes): show all types of theme definitions
  lib/components/displays/colors-data.ts
  lib/components/displays/colors.tsx
  pages/en-us/customization/themes.mdx
  pages/zh-cn/customization/themes.mdx
Labels: type: documentation

#59 fix(use-portal): don't remove shared element slot
  components/utils/use-portal.ts
Labels: bug

#60 docs: don't redirect to default page if pathname existed
  lib/components/menu/menu-sticker.tsx
Labels: type: documentation

#63 feat(image): add a prop to control max duration of image animation
  components/image/image.tsx
  pages/en-us/components/image.mdx
  pages/zh-cn/components/image.mdx
Labels: type: feature

#64 docs: reduce the weight of component name in chinese title
  lib/components/sidebar/active-link.tsx
  lib/components/sidebar/side-item.tsx
Labels: type: documentation

#67 feat(tooltip): add component
  components/index.ts
  components/text/child.tsx
  components/tooltip/index.ts
  components/tooltip/placement.ts
  components/tooltip/styles.ts
  components/tooltip/tooltip-content.tsx
  components/tooltip/tooltip-icon.tsx
  components/tooltip/tooltip.tsx
  components/utils/prop-types.ts
  package.json
  pages/en-us/components/tooltip.mdx
  pages/zh-cn/components/tooltip.mdx
Labels: type: feature

#69 docs(playground): show title on copy icon
  lib/components/playground/index.tsx
Labels: type: documentation

#70 docs(text): fix document example dose not match title
  pages/en-us/components/text.mdx
  pages/zh-cn/components/text.mdx
Labels: type: documentation

#71 feat(popover): add component
  components/index.ts
  components/popover/index.ts
  components/popover/popover-item.tsx
  components/popover/popover.tsx
  components/tooltip/tooltip-content.tsx
  components/tooltip/tooltip.tsx
  components/utils/collections.ts
  pages/en-us/components/popover.mdx
  pages/en-us/components/tooltip.mdx
  pages/zh-cn/components/popover.mdx
  pages/zh-cn/components/tooltip.mdx
Labels: type: feature

#72 fix: remove the background caused by the line-height of img
  components/display/display.tsx
  components/image/image.tsx
Labels: bug

#73 feat(themes): deep merge themes by default
  components/styles/theme-provider/theme-provider.tsx
  components/utils/types.d.ts
  package.json
Labels: type: feature

#74 docs(examples): add custom-themes sample
  examples/.gitkeep
  examples/custom-themes/README.md
  examples/custom-themes/package.json
  examples/custom-themes/public/index.html
  examples/custom-themes/src/home.jsx
  examples/custom-themes/src/index.jsx
  examples/custom-themes/src/theme.js
  examples/custom-themes/yarn.lock
  pages/en-us/guide/themes.mdx
  pages/zh-cn/guide/themes.mdx
Labels: type: documentation

#75 feat(card): append types to card
  components/card/card.tsx
  components/card/styles.ts
  components/utils/prop-types.ts
  pages/en-us/components/card.mdx
  pages/zh-cn/components/card.mdx
Labels: type: feature

#76 feat(tag): append types to tag component
  .eslintignore
  components/tag/tag.tsx
  pages/en-us/components/tag.mdx
  pages/zh-cn/components/tag.mdx
Labels: type: feature

#77 feat(image): add browser style
  components/display/display.tsx
  components/image/image-browser-https-icon.tsx
  components/image/image-browser.tsx
  components/image/image.tsx
  components/image/index.ts
  components/image/styles.ts
  pages/en-us/components/image.mdx
  pages/zh-cn/components/image.mdx
Labels: type: feature

#78 fix(image): limit the max width of the image on browser mode
  components/image/image-browser.tsx
Labels: bug

#79 feat(avatar): use group to display multiple avatars
  components/avatar/avatar-group.tsx
  components/avatar/avatar.tsx
  components/avatar/index.ts
  pages/en-us/components/avatar.mdx
  pages/zh-cn/components/avatar.mdx
Labels: type: feature

#80 docs: optimize the experience of switch of language and tabbar
  .eslintignore
  .gitignore
  lib/components/controls.tsx
  lib/components/layout.tsx
  lib/components/menu/menu-sticker.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/side-item.tsx
  lib/config-context.ts
  lib/config-provider.tsx
  lib/data/index.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  lib/use-locale.ts
  pages/_app.tsx
  pages/en-us/components/index.js
  pages/en-us/guide/index.js
  pages/zh-cn/components/index.js
  pages/zh-cn/guide/index.js
  scripts/collect-meta.js
  typings/meta.d.ts
Labels: type: documentation

#81 docs: add customization page
  components/auto-complete/auto-complete-empty.tsx
  components/auto-complete/auto-complete.tsx
  components/link/link.tsx
  components/popover/popover.tsx
  components/shared/dropdown.tsx
  components/styles/css-baseline/css-baseline.tsx
  components/styles/theme-provider/theme-provider.tsx
  components/styles/themes/dark.ts
  components/styles/themes/default.ts
  components/styles/themes/index.ts
  lib/components/attributes/attributes.tsx
  lib/components/controls.tsx
  lib/components/customization/codes.tsx
  lib/components/customization/colors.tsx
  lib/components/customization/demo.tsx
  lib/components/customization/editor-color-item.tsx
  lib/components/customization/editor-input-item.tsx
  lib/components/customization/editor.tsx
  lib/components/customization/layout.tsx
  lib/components/icons/full-screen-close.tsx
  lib/components/icons/full-screen.tsx
  lib/components/layout.tsx
  lib/components/menu/menu-sticker.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/side-item.tsx
  lib/components/sidebar/tabbar-mobile.tsx
  lib/config-context.ts
  lib/config-provider.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/en-us/components/auto-complete.mdx
  pages/en-us/customization/index.tsx
  pages/zh-cn/components/auto-complete.mdx
  pages/zh-cn/customization/index.tsx
  scripts/collect-meta.js
  yarn.lock
Labels: type: documentation

#84 docs: keep the theme perferences for visitors
  components/select/select.tsx
  components/shared/dropdown.tsx
  lib/components/controls.tsx
  lib/components/layout.tsx
  lib/components/menu/index.tsx
  lib/components/menu/menu-sticker.tsx
  lib/use-dom-clean.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/en-us/components/input.mdx
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
  yarn.lock
Labels: type: documentation, type: feature

#86 fix(union-type): fix union type overridden by default-props type
  components/col/col.tsx
  components/description/description.tsx
  components/display/display.tsx
  components/fieldset/fieldset.tsx
  components/input/input.tsx
  components/modal/modal-action.tsx
  components/note/note.tsx
  components/popover/popover-item.tsx
  components/popover/popover.tsx
  components/row/row.tsx
  components/select/select.tsx
  components/table/table.tsx
  components/tooltip/tooltip.tsx
  components/utils/with-defaults.ts
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: bug

#89 feat(link): display colors for links in dark mode
  components/styles/themes/dark.ts
Labels: type: feature, type: styles

#90 fix(select): limit the maximum height of the dropdown-menu
  components/select/select-dropdown.tsx
  components/select/select.tsx
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: bug

#91 chore(examples): add custom-styles
  examples/custom-styles/README.md
  examples/custom-styles/package.json
  examples/custom-styles/public/index.html
  examples/custom-styles/src/home.jsx
  examples/custom-styles/src/index.jsx
  examples/custom-styles/src/style.css
  examples/custom-styles/yarn.lock
Labels: type: chore

#94 feat(slider): add component
  components/index.ts
  components/slider/index.ts
  components/slider/slider-dot.tsx
  components/slider/slider-mark.tsx
  components/slider/slider.tsx
  components/utils/use-body-scroll.ts
  components/utils/use-drag.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/slider.mdx
  pages/zh-cn/components/slider.mdx
Labels: type: feature

#96 docs: show contributors on document site
  .circleci/config.yml
  .nowignore
  lib/components/attributes/attributes.tsx
  lib/data/contributors.json
  now.json
  package.json
  scripts/collect-contributors.js
  yarn.lock
Labels: type: documentation

#98 feat(divider): add component
  components/divider/divider.tsx
  components/divider/index.ts
  components/index.ts
  components/spacer/spacer.tsx
  components/utils/prop-types.ts
  lib/data/contributors.json
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/divider.mdx
  pages/zh-cn/components/divider.mdx
  scripts/collect-contributors.js
Labels: type: feature

#99 build: add scaffolding for test
  .circleci/config.yml
  .eslintignore
  .github/workflows/publish.yml
  .jest.config.js
  components/auto-complete/auto-complete.tsx
  components/badge/__tests__/__snapshots__/index.test.tsx.snap
  components/badge/__tests__/index.test.tsx
  components/file-tree/tree.tsx
  components/modal/use-modal.ts
  components/textarea/textarea.tsx
  package.json
  scripts/tsconfig.test.json
  tests/.babelrc.js
  tests/setup.js
  yarn.lock
Labels: type: chore, type: test

#101 refactor: replace static file with API to get contributors
  components/tooltip/tooltip-content.tsx
  lib/components/attributes/attributes.tsx
  lib/components/attributes/contributors.tsx
  lib/data/contributors.json
  now.json
  package.json
  scripts/collect-contributors.js
  yarn.lock
Labels: type: chore

#102 ci: report coverage to codecov.io
  .circleci/config.yml
  .jest.config.js
  components/avatar/__tests__/__snapshots__/index.test.tsx.snap
  components/avatar/__tests__/index.test.tsx
  components/avatar/avatar.tsx
  components/avatar/constants.ts
  components/capacity/__tests__/__snapshots__/index.test.tsx.snap
  components/capacity/__tests__/index.test.tsx
  package.json
Labels: type: test

#103 test(button): add testcase
  .jest.config.js
  components/button/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/index.test.tsx
  components/button/button.drip.tsx
  components/button/button.tsx
  package.json
  tests/.babelrc.js
  tests/utils.ts
  yarn.lock
Labels: type: test

#104 test(button-dropdown): add testcase
  components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
  components/button-dropdown/__tests__/index.test.tsx
  tests/utils.ts
Labels: type: test

#105 test(card): add testcase
  .codecov.yml
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/card/__tests__/index.test.tsx
  components/card/index.ts
Labels: type: test

#106 test(checkbox): add testcase
  components/checkbox/__tests__/__snapshots__/group.test.tsx.snap
  components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  components/checkbox/__tests__/group.test.tsx
  components/checkbox/__tests__/index.test.tsx
  components/checkbox/checkbox-context.ts
  components/checkbox/checkbox.tsx
Labels: type: test

#107 test(auto-complete): add testcase
  components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/__tests__/search.test.tsx
  components/auto-complete/auto-complete-context.ts
  components/auto-complete/auto-complete-dropdown.tsx
  components/auto-complete/auto-complete-item.tsx
  components/auto-complete/auto-complete.tsx
Labels: type: test

#108 feat(user): add component
  components/index.ts
  components/user/__tests__/__snapshots__/index.test.tsx.snap
  components/user/__tests__/index.test.tsx
  components/user/index.ts
  components/user/user-link.tsx
  components/user/user.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/user.mdx
  pages/zh-cn/components/user.mdx
Labels: type: feature

#109 test(code): add testcase
  components/code/__tests__/__snapshots__/index.test.tsx.snap
  components/code/__tests__/index.test.tsx
  components/styles/css-baseline/css-baseline.tsx
Labels: type: test

#111 build: move styled-jsx to dependencies
  package.json
  scripts/webpack.config.js
Labels: type: chore

#112 test(col): add testcase
  .jest.config.js
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/__tests__/search.test.tsx
  components/avatar/__tests__/index.test.tsx
  components/button-dropdown/__tests__/index.test.tsx
  components/button/__tests__/index.test.tsx
  components/capacity/__tests__/index.test.tsx
  components/card/__tests__/index.test.tsx
  components/checkbox/__tests__/group.test.tsx
  components/checkbox/__tests__/index.test.tsx
  components/code/__tests__/index.test.tsx
  components/col/__tests__/__snapshots__/index.test.tsx.snap
  components/col/__tests__/index.test.tsx
  components/collapse/__tests__/__snapshots__/group.test.tsx.snap
  components/collapse/__tests__/__snapshots__/index.test.tsx.snap
  components/collapse/__tests__/group.test.tsx
  components/collapse/__tests__/index.test.tsx
  components/collapse/collapse-group.tsx
  components/collapse/collapse.tsx
  components/description/__tests__/__snapshots__/index.test.tsx.snap
  components/description/__tests__/index.test.tsx
  components/display/__tests__/__snapshots__/index.test.tsx.snap
  components/display/__tests__/index.test.tsx
  components/divider/__tests__/__snapshots__/index.test.tsx.snap
  components/divider/__tests__/index.test.tsx
  components/user/__tests__/index.test.tsx
  tests/utils.ts
Labels: type: test

#113 test: add testcase
  components/dot/__tests__/__snapshots__/index.test.tsx.snap
  components/dot/__tests__/index.test.tsx
  components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
  components/fieldset/__tests__/group.test.tsx
  components/fieldset/__tests__/index.test.tsx
  components/fieldset/fieldset.tsx
  components/file-tree/__tests__/__snapshots__/index.test.tsx.snap
  components/file-tree/__tests__/index.test.tsx
  components/image/__tests__/__snapshots__/browser.test.tsx.snap
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/browser.test.tsx
  components/image/__tests__/index.test.tsx
Labels: type: test

#114 fix(display): hide shadow on dark mode
  .circleci/config.yml
  components/display/display.tsx
Labels: bug

#115 test(tag): add testcase
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/tag/__tests__/index.test.tsx
  components/tag/tag.tsx
Labels: bug, type: test

#116 feat(image): forward ref for image browser
  components/image/image-browser.tsx
Labels: type: feature

#117 fix(slider): fix excessive offset when sync custom value
  components/slider/slider.tsx
  pages/en-us/components/slider.mdx
  pages/zh-cn/components/slider.mdx
Labels: bug

#118 test(input): add testcase
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/index.test.tsx
  components/input/__tests__/use-input.test.tsx
  components/input/input-icon-clear.tsx
  components/input/input.tsx
  components/keyboard/__tests__/__snapshots__/index.test.tsx.snap
  components/keyboard/__tests__/index.test.tsx
  components/link/__tests__/__snapshots__/index.test.tsx.snap
  components/link/__tests__/index.test.tsx
  components/loading/__tests__/__snapshots__/index.test.tsx.snap
  components/loading/__tests__/index.test.tsx
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/__tests__/index.test.tsx
  components/modal/__tests__/use-modal.test.tsx
  components/modal/modal-context.ts
  components/modal/modal.tsx
Labels: type: test

#119 fix(module): fix the default export module file
  package.json
Labels: bug

#121 feat(card): add footer component
  components/card/__tests__/__snapshots__/footer.test.tsx.snap
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/card/__tests__/footer.test.tsx
  components/card/card-footer.tsx
  components/card/card.tsx
  components/card/index.ts
  pages/en-us/components/card.mdx
  pages/zh-cn/components/card.mdx
Labels: type: feature

#122 test: add testcase
  components/note/__tests__/__snapshots__/index.test.tsx.snap
  components/note/__tests__/index.test.tsx
  components/popover/__tests__/__snapshots__/index.test.tsx.snap
  components/popover/__tests__/index.test.tsx
  components/progress/__tests__/__snapshots__/index.test.tsx.snap
  components/progress/__tests__/index.test.tsx
Labels: type: test

#123 test: add test cases
  components/radio/__tests__/__snapshots__/group.test.tsx.snap
  components/radio/__tests__/__snapshots__/index.test.tsx.snap
  components/radio/__tests__/group.test.tsx
  components/radio/__tests__/index.test.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/row/__tests__/__snapshots__/index.test.tsx.snap
  components/row/__tests__/index.test.tsx
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/index.test.tsx
  components/select/select-option.tsx
Labels: type: test

#124 feat(image): auto scale image when width is too small
  components/image/__tests__/index.test.tsx
  components/image/image.tsx
  pages/en-us/components/display.mdx
  pages/en-us/components/image.mdx
  pages/zh-cn/components/display.mdx
  pages/zh-cn/components/image.mdx
Labels: type: feature

#127 fix(modal): fix styles to follow design guide
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/modal-title.tsx
  components/modal/modal-wrapper.tsx
  components/shared/backdrop.tsx
  components/styles/themes/dark.ts
  lib/components/menu/menu-sticker.tsx
  lib/components/sidebar/tabbar-mobile.tsx
Labels: bug, type: styles

#128 test: add test cases
  components/slider/__tests__/__snapshots__/index.test.tsx.snap
  components/slider/__tests__/index.test.tsx
  components/slider/slider.tsx
  components/snippet/__tests__/__snapshots__/index.test.tsx.snap
  components/snippet/__tests__/index.test.tsx
  components/snippet/snippet.tsx
  pages/en-us/components/snippet.mdx
  pages/zh-cn/components/snippet.mdx
Labels: bug, type: test

#130 test: add test cases
  components/spacer/__tests__/__snapshots__/index.test.tsx.snap
  components/spacer/__tests__/index.test.tsx
  components/spacer/spacer.tsx
  components/spinner/__tests__/__snapshots__/index.test.tsx.snap
  components/spinner/__tests__/index.test.tsx
Labels: type: test

#131 test: add test cases
  components/table/__tests__/__snapshots__/index.test.tsx.snap
  components/table/__tests__/index.test.tsx
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/__tests__/index.test.tsx
  components/tabs/__tests__/use-tabs.test.tsx
Labels: type: test

#132 test: add test cases
  components/textarea/__tests__/__snapshots__/index.test.tsx.snap
  components/textarea/__tests__/index.test.tsx
  components/toast/__tests__/__snapshots__/index.test.tsx.snap
  components/toast/__tests__/index.test.tsx
  components/toast/toast-item.tsx
  components/toast/use-toast.tsx
  components/toggle/__tests__/__snapshots__/index.test.tsx.snap
  components/toggle/__tests__/index.test.tsx
Labels: type: test

#133 chore: add test cases and export utils
  components/index.ts
  components/modal/__tests__/use-modal.test.tsx
  components/modal/modal-action.tsx
  components/text/__tests__/__snapshots__/index.test.tsx.snap
  components/text/__tests__/index.test.tsx
  components/utils/__tests__/calculations.test.tsx
  components/utils/index.ts
  package.json
Labels: type: chore, type: test

#129 test(tooltip): add testcase
  components/tooltip/__test__/index.test.tsx
Labels: type: test

#135 docs: rename the referenced ZEIT brand name in docs
  README.md
  package.json
  pages/en-us/guide/introduction.mdx
  pages/zh-cn/guide/introduction.mdx
  yarn.lock
Labels: type: documentation

#136 test(styles): add testcase
  components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
  components/styles/__tests__/__snapshots__/theme-provider.test.tsx.snap
  components/styles/__tests__/baseline.test.tsx
  components/styles/__tests__/theme-provider.test.tsx
Labels: type: test

#137 fix: fix input styles and baseline
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/input.tsx
  components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
  components/styles/css-baseline/css-baseline.tsx
  components/textarea/__tests__/__snapshots__/index.test.tsx.snap
  components/textarea/textarea.tsx
  pages/_app.tsx
Labels: bug

#139 feat(icons): link icons through CSS variables
  components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
  components/styles/css-baseline/css-baseline.tsx
Labels: type: feature

#140 test: remove unused default-values
  components/button/button.drip.tsx
  components/fieldset/fieldset-context.ts
  components/fieldset/fieldset-group.tsx
  components/fieldset/fieldset.tsx
  components/file-tree/tree-context.ts
  components/file-tree/tree-file.tsx
  components/modal/modal-action.tsx
  components/modal/modal-context.ts
Labels: type: test

#141 docs: use zeit-icons instead of svg icons
  lib/components/controls.tsx
  lib/components/icons/arrow.tsx
  lib/components/icons/copy.tsx
  lib/components/icons/full-screen-close.tsx
  lib/components/icons/full-screen.tsx
  lib/components/icons/github.tsx
  lib/components/icons/moon.tsx
  lib/components/icons/react.tsx
  lib/components/icons/refresh.tsx
  lib/components/icons/right.tsx
  lib/components/icons/sun.tsx
  lib/components/icons/toggle.tsx
  lib/components/icons/zeit.tsx
  lib/components/playground/index.tsx
  lib/components/sidebar/tabbar-mobile.tsx
  package.json
  pages/en-us/components/input.mdx
  pages/en-us/components/tabs.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/tabs.mdx
  yarn.lock
Labels: type: documentation

#143 feat(text): add blockquote
  .jest.config.js
  components/styles/__tests__/__snapshots__/baseline.test.tsx.snap
  components/styles/css-baseline/css-baseline.tsx
  components/text/__tests__/__snapshots__/index.test.tsx.snap
  components/text/child.tsx
  components/text/text.tsx
  pages/en-us/components/text.mdx
  pages/zh-cn/components/text.mdx
Labels: type: feature

#145 feat(input): add password
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/__snapshots__/password.test.tsx.snap
  components/input/__tests__/index.test.tsx
  components/input/__tests__/password.test.tsx
  components/input/index.ts
  components/input/input-icon.tsx
  components/input/input-props.ts
  components/input/input.tsx
  components/input/password-icon.tsx
  components/input/password.tsx
  pages/en-us/components/input.mdx
  pages/zh-cn/components/input.mdx
Labels: type: feature

#147 feat(card): extract content wrapper
  components/card/__tests__/__snapshots__/footer.test.tsx.snap
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/card/__tests__/index.test.tsx
  components/card/card-content.tsx
  components/card/card.tsx
  components/card/index.ts
  pages/en-us/components/card.mdx
  pages/zh-cn/components/card.mdx
Labels: type: feature

#148 feat(text): add size to specify the text size
  components/styles/__tests__/__snapshots__/theme-provider.test.tsx.snap
  components/text/__tests__/__snapshots__/index.test.tsx.snap
  components/text/__tests__/index.test.tsx
  components/text/child.tsx
  components/text/text.tsx
  pages/en-us/components/text.mdx
  pages/zh-cn/components/text.mdx
Labels: type: feature

#149 feat(fieldset): extract content wrapper
  components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
  components/fieldset/__tests__/index.test.tsx
  components/fieldset/fieldset-content.tsx
  components/fieldset/fieldset-footer.tsx
  components/fieldset/fieldset.tsx
  components/fieldset/index.ts
  pages/en-us/components/fieldset.mdx
  pages/zh-cn/components/fieldset.mdx
Labels: type: feature

#151 fix(input): fix color of fill text
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/__snapshots__/password.test.tsx.snap
  components/input/input.tsx
Labels: bug

#155 fix: prevent main color change in special types
  components/note/__tests__/__snapshots__/index.test.tsx.snap
  components/note/note.tsx
  components/toast/__tests__/__snapshots__/index.test.tsx.snap
  components/toast/toast-item.tsx
Labels: bug

#157 build: bundle in cjs mode is not compressed by default
  package.json
  rollup.config.js
  scripts/webpack.config.js
  yarn.lock
Labels: type: chore

#158 feat(badge): supoort to anchor with other components
  components/badge/__tests__/__snapshots__/anchor.test.tsx.snap
  components/badge/__tests__/__snapshots__/index.test.tsx.snap
  components/badge/__tests__/anchor.test.tsx
  components/badge/__tests__/index.test.tsx
  components/badge/badge-anchor.tsx
  components/badge/badge.tsx
  components/badge/index.ts
  pages/en-us/components/badge.mdx
  pages/zh-cn/components/badge.mdx
Labels: type: feature
