Repository geist-org/geist-ui, pull requests merged in 2020-06, with the labels that each got.

#253 feat: add Breadcrumbs component
  components/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  components/breadcrumbs/__tests__/breadcrumbs.test.tsx
  components/breadcrumbs/breadcrumbs-item.tsx
  components/breadcrumbs/breadcrumbs-separator.tsx
  components/breadcrumbs/breadcrumbs.tsx
  components/breadcrumbs/index.ts
  components/index.ts
  components/link/link.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/breadcrumbs.mdx
  pages/zh-cn/components/breadcrumbs.mdx
Labels: type: feature

#257 feat(use-input): compatible with components of non-standed events
  components/auto-complete/__tests__/use-input.test.tsx
  components/input/use-input.ts
Labels: type: feature

#261 Pagination
  components/index.ts
  components/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
  components/pagination/__tests__/pagination.test.tsx
  components/pagination/index.ts
  components/pagination/pagination-context.ts
  components/pagination/pagination-ellipsis.tsx
  components/pagination/pagination-item.tsx
  components/pagination/pagination-next.tsx
  components/pagination/pagination-pages.tsx
  components/pagination/pagination-previous.tsx
  components/pagination/pagination.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/pagination.mdx
  pages/zh-cn/components/pagination.mdx
Labels: type: feature

#265 fix(backdrop): fix click events from content to close modal unexpectedly
  components/shared/__tests__/backdrop.test.tsx
  components/shared/backdrop.tsx
Labels: bug

#267 chore(examples): add example for tree-shaking with next
  .gitignore
  examples/tree-shaking-nextjs/.babelrc
  examples/tree-shaking-nextjs/README.md
  examples/tree-shaking-nextjs/next.config.js
  examples/tree-shaking-nextjs/package.json
  examples/tree-shaking-nextjs/pages/_app.js
  examples/tree-shaking-nextjs/pages/_document.js
  examples/tree-shaking-nextjs/pages/index.js
  examples/tree-shaking-nextjs/public/favicon.ico
  examples/tree-shaking-nextjs/public/output-after.png
  examples/tree-shaking-nextjs/public/output-before.png
Labels: type: documentation

#271 feat(radio): support for number type
  components/radio/__tests__/group.test.tsx
  components/radio/radio-context.ts
  components/radio/radio-group.tsx
  components/radio/radio.tsx
Labels: type: feature

#274 feat(image): pass through all props of anchor element
  components/image/__tests__/browser.test.tsx
  components/image/image-browser.tsx
  pages/en-us/components/image.mdx
  pages/zh-cn/components/image.mdx
Labels: type: feature

#276 feat(baseline): optimize fontSize of block code
  components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
  components/css-baseline/css-baseline.tsx
Labels: type: feature, type: styles

#279 docs: grammar updates to en-us guides
  pages/en-us/guide/colors.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/introduction.mdx
  pages/en-us/guide/server-render.mdx
  pages/en-us/guide/themes.mdx
Labels: type: documentation

#281 chore: release v1.7.0
  components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/__tests__/search.test.tsx
  components/auto-complete/__tests__/use-input.test.tsx
  components/auto-complete/auto-complete-item.tsx
  components/auto-complete/auto-complete.tsx
  components/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap
  components/breadcrumbs/__tests__/breadcrumbs.test.tsx
  components/breadcrumbs/breadcrumbs-item.tsx
  components/breadcrumbs/breadcrumbs-separator.tsx
  components/breadcrumbs/breadcrumbs.tsx
  components/breadcrumbs/index.ts
  components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
  components/css-baseline/css-baseline.tsx
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/__tests__/index.test.tsx
  components/grid/basic-item.tsx
  components/image/__tests__/browser.test.tsx
  components/image/image-browser.tsx
  components/index.ts
  components/input/use-input.ts
  components/link/link.tsx
  components/pagination/__tests__/__snapshots__/pagination.test.tsx.snap
  components/pagination/__tests__/pagination.test.tsx
  components/pagination/index.ts
  components/pagination/pagination-context.ts
  components/pagination/pagination-ellipsis.tsx
  components/pagination/pagination-item.tsx
  components/pagination/pagination-next.tsx
  components/pagination/pagination-pages.tsx
  components/pagination/pagination-previous.tsx
  components/pagination/pagination.tsx
  components/radio/__tests__/group.test.tsx
  components/radio/radio-context.ts
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  package.json
  pages/en-us/components/auto-complete.mdx
  pages/en-us/components/breadcrumbs.mdx
  pages/en-us/components/grid.mdx
  pages/en-us/components/image.mdx
  pages/en-us/components/pagination.mdx
  pages/zh-cn/components/auto-complete.mdx
  pages/zh-cn/components/breadcrumbs.mdx
  pages/zh-cn/components/grid.mdx
  pages/zh-cn/components/image.mdx
  pages/zh-cn/components/pagination.mdx
Labels: type: chore

#282 docs(colors): optimize colors page
  components/badge/__tests__/__snapshots__/index.test.tsx.snap
  components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
  components/capacity/__tests__/__snapshots__/index.test.tsx.snap
  components/dot/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/basic-item.tsx
  components/loading/__tests__/__snapshots__/index.test.tsx.snap
  components/note/__tests__/__snapshots__/index.test.tsx.snap
  components/progress/__tests__/__snapshots__/index.test.tsx.snap
  components/styles/themes/dark.ts
  components/styles/themes/default.ts
  components/styles/themes/index.ts
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/text/__tests__/__snapshots__/index.test.tsx.snap
  lib/components/displays/colors-data.ts
  lib/components/displays/colors.tsx
  pages/en-us/guide/colors.mdx
Labels: bug, type: documentation

#283 fix(modal): fix height constraint of modal
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/modal-actions.tsx
  components/modal/modal-content.tsx
  components/modal/modal-title.tsx
  components/modal/modal-wrapper.tsx
  components/modal/modal.tsx
  components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
  components/shared/__tests__/backdrop.test.tsx
  components/shared/backdrop.tsx
Labels: bug

#286 chore: release v1.7.2
  components/badge/__tests__/__snapshots__/index.test.tsx.snap
  components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
  components/capacity/__tests__/__snapshots__/index.test.tsx.snap
  components/dot/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/basic-item.tsx
  components/loading/__tests__/__snapshots__/index.test.tsx.snap
  components/note/__tests__/__snapshots__/index.test.tsx.snap
  components/progress/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/styles/themes/dark.ts
  components/styles/themes/default.ts
  components/styles/themes/index.ts
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/text/__tests__/__snapshots__/index.test.tsx.snap
  lib/components/displays/colors-data.ts
  lib/components/displays/colors.tsx
  package.json
  pages/en-us/guide/colors.mdx
Labels: type: chore

#287 feat(snippet): add custom symbol and toast
  components/snippet/__tests__/__snapshots__/index.test.tsx.snap
  components/snippet/__tests__/index.test.tsx
  components/snippet/snippet.tsx
  pages/en-us/components/snippet.mdx
Labels: type: feature

#288 docs: improve APIs of components
  pages/en-us/components/snippet.mdx
  pages/en-us/components/toast.mdx
  pages/zh-cn/components/snippet.mdx
  pages/zh-cn/components/toast.mdx
Labels: type: documentation

#290 fix(ellipsis): set the height of ellipsis manually
  components/auto-complete/auto-complete-item.tsx
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/select-option.tsx
  components/select/select.tsx
  components/shared/__tests__/__snapshots__/ellipsis.test.tsx.snap
  components/shared/__tests__/ellipsis.test.tsx
  components/shared/ellipsis.tsx
Labels: bug

#293 fix(slider): fix the bug causing offset is out of bounds
  components/slider/slider.tsx
Labels: bug

#299 docs: format unique abbreviations
  lib/components/controls.tsx
Labels: type: documentation

#303 chore(gh): update GitHub templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-docs.md
  .github/ISSUE_TEMPLATE/3-styles.md
  .github/ISSUE_TEMPLATE/4-docs.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: chore
