Repository geist-org/geist-ui, pull requests merged in 2020-08, with the labels that each got.

#354 feat(modal): lock tab action inside modal
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/button.tsx
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/__tests__/index.test.tsx
  components/modal/modal-action.tsx
  components/modal/modal-wrapper.tsx
  components/shared/backdrop.tsx
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  components/utils/collections.ts
Labels: type: feature

#362 fix(table): fix column's props are not tracked
  components/table/__tests__/index.test.tsx
  components/table/table-column.tsx
  components/table/table-context.ts
  components/table/table.tsx
Labels: bug

#364 fix(table): children of column should be kept in sync
  components/table/__tests__/index.test.tsx
  components/table/table-column.tsx
Labels: bug

#367 chore: release v1.8.0
  components/button-group/__tests__/__snapshots__/index.test.tsx.snap
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/__tests__/icon.test.tsx
  components/button/button-icon.tsx
  components/button/button.tsx
  components/button/utils.tsx
  components/description/description.tsx
  components/image/__tests__/browser.test.tsx
  components/input/input.tsx
  components/link/__tests__/__snapshots__/index.test.tsx.snap
  components/link/link.tsx
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
  components/modal/__tests__/index.test.tsx
  components/modal/modal-action.tsx
  components/modal/modal-actions.tsx
  components/modal/modal-content.tsx
  components/modal/modal-wrapper.tsx
  components/popover/popover-item.tsx
  components/select/select-dropdown.tsx
  components/select/select.tsx
  components/shared/__tests__/__snapshots__/backdrop.test.tsx.snap
  components/shared/__tests__/dropdown.test.tsx
  components/shared/backdrop.tsx
  components/shared/dropdown.tsx
  components/snippet/__tests__/__snapshots__/index.test.tsx.snap
  components/snippet/__tests__/index.test.tsx
  components/snippet/snippet.tsx
  components/table/__tests__/index.test.tsx
  components/table/table-column.tsx
  components/table/table-context.ts
  components/table/table.tsx
  components/tabs/__tests__/index.test.tsx
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  components/textarea/__tests__/__snapshots__/index.test.tsx.snap
  components/textarea/textarea.tsx
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  components/utils/collections.ts
  components/utils/use-portal.ts
  lib/components/menu/menu-links.tsx
  package.json
  pages/en-us/components/button.mdx
  pages/en-us/components/input.mdx
  pages/en-us/components/link.mdx
  pages/en-us/components/modal.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/snippet.mdx
  pages/en-us/components/tabs.mdx
  pages/en-us/components/textarea.mdx
  pages/en-us/components/toast.mdx
  pages/zh-cn/components/button.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/link.mdx
  pages/zh-cn/components/modal.mdx
  pages/zh-cn/components/select.mdx
  pages/zh-cn/components/snippet.mdx
  pages/zh-cn/components/tabs.mdx
  pages/zh-cn/components/textarea.mdx
  pages/zh-cn/components/toast.mdx
Labels: type: chore

#368 docs: add logo image
  lib/components/icons/logo.tsx
  pages/en-us/guide/introduction.mdx
  pages/zh-cn/guide/introduction.mdx
  public/images/logo.png
Labels: type: documentation

#376 fix(checkbox): fix export type
  components/checkbox/checkbox.tsx
Labels: bug

#377 docs(image): fix image types
  .github/CONTRIBUTING.md
  pages/en-us/components/image.mdx
Labels: type: documentation

#379 docs: improve og-title
  pages/_app.tsx
Labels: type: documentation
