Repository geist-org/geist-ui, pull requests merged in 2021-06, with the labels that each got.

#530 feat: add status prop in checkbox, radio, select, slider and toggle
  components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/auto-complete.tsx
  components/badge/badge.tsx
  components/button-group/button-group.tsx
  components/button/utils.tsx
  components/checkbox/__tests__/__snapshots__/index.test.tsx.snap
  components/checkbox/__tests__/index.test.tsx
  components/checkbox/checkbox.icon.tsx
  components/checkbox/checkbox.tsx
  components/checkbox/styles.ts
  components/divider/divider.tsx
  components/image/styles.ts
  components/input/__tests__/index.test.tsx
  components/input/input-props.ts
  components/input/input.tsx
  components/input/password.tsx
  components/loading/loading.tsx
  components/progress/progress.tsx
  components/radio/__tests__/__snapshots__/index.test.tsx.snap
  components/radio/__tests__/index.test.tsx
  components/radio/radio-group.tsx
  components/radio/radio.tsx
  components/radio/styles.ts
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/__tests__/index.test.tsx
  components/select/select.tsx
  components/select/styles.ts
  components/slider/__tests__/__snapshots__/index.test.tsx.snap
  components/slider/__tests__/index.test.tsx
  components/slider/slider.tsx
  components/slider/styles.ts
  components/snippet/styles.ts
  components/table/__tests__/index.test.tsx
  components/textarea/__tests__/index.test.tsx
  components/textarea/textarea.tsx
  components/toggle/__tests__/__snapshots__/index.test.tsx.snap
  components/toggle/__tests__/index.test.tsx
  components/toggle/styles.ts
  components/toggle/toggle.tsx
  components/tree/__tests__/index.test.tsx
  pages/en-us/components/auto-complete.mdx
  pages/en-us/components/checkbox.mdx
  pages/en-us/components/input.mdx
  pages/en-us/components/radio.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/slider.mdx
  pages/en-us/components/textarea.mdx
  pages/en-us/components/toggle.mdx
Labels: type: feature

#558 feat(auto-complete): add props for popup container
  components/auto-complete/auto-complete-dropdown.tsx
  components/auto-complete/auto-complete.tsx
  components/shared/dropdown.tsx
  pages/en-us/components/auto-complete.mdx
  pages/zh-cn/components/auto-complete.mdx
Labels: type: feature

#563 fix(bundle): fix modules missing in yarn berry
  .jest.config.js
  components/avatar/__tests__/index.test.tsx
  package.json
  yarn.lock
Labels: bug

#564 chore(examples): upgrade next examples for scaleable
  examples/create-next-app/.gitignore
  examples/create-next-app/README.md
  examples/create-next-app/next-env.d.ts
  examples/create-next-app/next.config.js
  examples/create-next-app/package.json
  examples/create-next-app/pages/_app.tsx
  examples/create-next-app/pages/index.js
  examples/create-next-app/pages/index.tsx
  examples/create-next-app/public/geist-banner.png
  examples/create-next-app/tsconfig.json
Labels: type: chore

#543 feat(rating): a new component rating indicator
  components/index.ts
  components/rating/__tests__/__snapshots__/index.test.tsx.snap
  components/rating/__tests__/index.test.tsx
  components/rating/index.ts
  components/rating/rating-icon.tsx
  components/rating/rating.tsx
  components/utils/prop-types.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  next-env.d.ts
  package-lock.json
  pages/en-us/components/rating.mdx
  pages/zh-cn/components/rating.mdx
  yarn.lock
Labels: type: feature

#569 refactor(table): redesign interfaces to improve the experience in TypeScript
  components/rating/rating.tsx
  components/table/__tests__/__snapshots__/index.test.tsx.snap
  components/table/__tests__/index.test.tsx
  components/table/index.ts
  components/table/table-body.tsx
  components/table/table-cell.tsx
  components/table/table-column.tsx
  components/table/table-context.ts
  components/table/table-head.tsx
  components/table/table-types.ts
  components/table/table.tsx
  lib/components/index.ts
  pages/en-us/components/table.mdx
  pages/en-us/components/use-media-query.mdx
  pages/zh-cn/components/table.mdx
  pages/zh-cn/components/use-media-query.mdx
Labels: type: feature

#570 docs: fix sidebar text-transform
  lib/components/sidebar/active-link.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/auto-complete.mdx
  pages/en-us/components/avatar.mdx
  pages/en-us/components/breadcrumbs.mdx
  pages/en-us/components/button-dropdown.mdx
  pages/en-us/components/button-group.mdx
  pages/en-us/components/button.mdx
  pages/en-us/components/card.mdx
  pages/en-us/components/checkbox.mdx
  pages/en-us/components/collapse.mdx
  pages/en-us/components/fieldset.mdx
  pages/en-us/components/file-tree.mdx
  pages/en-us/components/grid.mdx
  pages/en-us/components/keyboard.mdx
  pages/en-us/components/link.mdx
  pages/en-us/components/modal.mdx
  pages/en-us/components/note.mdx
  pages/en-us/components/page.mdx
  pages/en-us/components/radio.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/spacer.mdx
  pages/en-us/components/tabs.mdx
  pages/en-us/components/text.mdx
  pages/en-us/components/textarea.mdx
  pages/en-us/components/toast.mdx
  pages/en-us/components/use-body-scroll.mdx
  pages/en-us/components/use-click-away.mdx
  pages/en-us/components/use-clipboard.mdx
  pages/en-us/components/use-current-state.mdx
  pages/en-us/components/use-keyboard.mdx
  pages/en-us/components/use-media-query.mdx
  pages/en-us/customization/index.tsx
  pages/en-us/guide/colors.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/introduction.mdx
  pages/en-us/guide/scaleable.mdx
  pages/en-us/guide/server-render.mdx
  pages/en-us/guide/themes.mdx
  pages/zh-cn/components/auto-complete.mdx
  pages/zh-cn/components/button-group.mdx
  pages/zh-cn/components/use-body-scroll.mdx
  pages/zh-cn/components/use-click-away.mdx
  pages/zh-cn/components/use-clipboard.mdx
  pages/zh-cn/components/use-current-state.mdx
  pages/zh-cn/components/use-keyboard.mdx
  pages/zh-cn/components/use-media-query.mdx
Labels: type: documentation

#571 docs: improve the copywriting content of the document
  components/use-toasts/index.ts
  components/use-toasts/use-toast.tsx
  lib/components/layout.tsx
  lib/components/menu/menu-links.tsx
  lib/components/menu/menu-sticker.tsx
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/active-link.tsx
  lib/components/sidebar/index.tsx
  lib/components/sidebar/tabbar-mobile.tsx
  lib/data/metadata-en-us.json
  pages/_app.tsx
  pages/en-us/components/auto-complete.mdx
  pages/en-us/components/badge.mdx
  pages/en-us/components/button-dropdown.mdx
  pages/en-us/components/card.mdx
  pages/en-us/components/checkbox.mdx
  pages/en-us/components/dot.mdx
  pages/en-us/components/fieldset.mdx
  pages/en-us/components/input.mdx
  pages/en-us/components/link.mdx
  pages/en-us/components/loading.mdx
  pages/en-us/components/note.mdx
  pages/en-us/components/progress.mdx
  pages/en-us/components/radio.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/slider.mdx
  pages/en-us/components/snippet.mdx
  pages/en-us/components/tabs.mdx
  pages/en-us/components/text.mdx
  pages/en-us/components/textarea.mdx
  pages/en-us/components/toast.mdx
  pages/en-us/components/toggle.mdx
  pages/en-us/components/tooltip.mdx
  pages/en-us/components/user.mdx
  pages/zh-cn/components/auto-complete.mdx
  pages/zh-cn/components/badge.mdx
  pages/zh-cn/components/button-dropdown.mdx
  pages/zh-cn/components/dot.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/loading.mdx
  pages/zh-cn/components/note.mdx
  pages/zh-cn/components/progress.mdx
  pages/zh-cn/components/snippet.mdx
  pages/zh-cn/components/text.mdx
  pages/zh-cn/components/textarea.mdx
  pages/zh-cn/components/toast.mdx
  pages/zh-cn/components/tooltip.mdx
  pages/zh-cn/components/user.mdx
Labels: type: documentation

#574 feat(modal): responds to keyboard events when modal is displayed
  components/modal/__tests__/index.test.tsx
  components/modal/index.ts
  components/modal/modal.tsx
  components/modal/use-modal.ts
  pages/en-us/components/modal.mdx
  pages/zh-cn/components/modal.mdx
Labels: type: feature

#576 docs: redesign mobile navigation
  lib/components/layout.tsx
  lib/components/sidebar/active-catalog.tsx
  lib/components/sidebar/active-link.tsx
  lib/components/sidebar/tabbar-mobile.tsx
Labels: type: documentation, type: styles

#579 feat(select): imporve the focus events to export simulated ref
  components/select/__tests__/__snapshots__/index.test.tsx.snap
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  components/select/__tests__/events.test.tsx
  components/select/__tests__/index.test.tsx
  components/select/index.ts
  components/select/select-dropdown.tsx
  components/select/select-input.tsx
  components/select/select-option.tsx
  components/select/select.tsx
  components/select/styles.ts
  components/shared/dropdown.tsx
  pages/en-us/components/select.mdx
  pages/zh-cn/components/select.mdx
Labels: type: feature
