Repository geist-org/geist-ui, pull requests merged in 2021-08, with the labels that each got.

#575 feat(drawer): create component
  .jest.config.js
  components/drawer/__tests__/__snapshots__/index.test.tsx.snap
  components/drawer/__tests__/index.test.tsx
  components/drawer/__tests__/use-modal.test.tsx
  components/drawer/drawer-wrapper.tsx
  components/drawer/drawer.tsx
  components/drawer/helper.ts
  components/drawer/index.ts
  components/index.ts
  components/modal/__tests__/index.test.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  package.json
  pages/en-us/components/drawer.mdx
  pages/zh-cn/components/drawer.mdx
  tests/setup.ts
  yarn.lock
Labels: type: feature

#603 fix: migrate the hooks file path in esm
  components/index.ts
  components/input/index.ts
  components/modal/__tests__/index.test.tsx
  components/modal/index.ts
  components/use-input/__tests__/use-input.test.tsx
  components/use-input/index.ts
  components/use-input/use-input.tsx
  components/use-modal/__tests__/use-modal.test.tsx
  components/use-modal/index.ts
  components/use-modal/use-modal.ts
  components/use-tabs/__tests__/use-tabs.test.tsx
  components/use-tabs/index.ts
  components/use-tabs/use-tabs.ts
Labels: bug

#605 fix(playground): hide webkit arrow icon
  lib/components/playground/editor.tsx
Labels: bug, type: styles
