Repository geist-org/geist-ui, pull requests merged in 2021-04, with the labels that each got.

#510 fix: fieldset title/subtitle use block element
  components/fieldset/__tests__/__snapshots__/index.test.tsx.snap
  components/fieldset/fieldset-subtitle.tsx
  components/fieldset/fieldset-title.tsx
Labels: bug

#511 docs: add secret repo as an example
  README.md
Labels: type: documentation

#520 chore(deps): update styled-jsx to ^3.3.1
  components/css-baseline/css-baseline.tsx
  components/grid/grid-container.tsx
  components/grid/grid.tsx
  components/modal/modal-action.tsx
  lib/components/icons/logo.tsx
  package.json
  tests/__mocks__/styled-jsx/css.js
  yarn.lock
Labels: bug, dependencies, type: chore

#525 build: ignore the example folder when build document site
  tsconfig.json
Labels: type: chore
