Repository geist-org/geist-ui, pull requests merged in 2021-02, with the labels that each got.

#439 feat(hooks): add a tool hooks for react context
  components/utils/__tests__/context-state.test.tsx
  components/utils/collections.ts
  components/utils/use-context-state/create-geist-context.tsx
  components/utils/use-context-state/use-context-state.ts
Labels: type: feature

#442 fix: remove unnecessary style in xs grid class
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/basic-item.tsx
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
Labels: bug

#452 chore: release v2.1.1
  package.json
  yarn.lock
Labels: type: chore

#457 fix(grid): fix the invalid property of flex in the default scene
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/basic-item.tsx
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
  package.json
Labels: bug

#458 fix default value of direction prop
  pages/en-us/components/grid.mdx
Labels: type: documentation

#460 fix(tabs): remove the scrollbar of the tab container
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs.tsx
Labels: bug

#461 fix(snippet): fix typo of copy type
  components/snippet/snippet.tsx
  components/utils/prop-types.ts
  pages/en-us/components/snippet.mdx
  pages/zh-cn/components/snippet.mdx
Labels: bug, type: documentation
