Repository geist-org/geist-ui, pull requests merged in 2021-03, with the labels that each got.

#478 docs(breakpoints): upgrade documentatino to match the new theme system
  pages/en-us/components/grid.mdx
  pages/en-us/components/use-media-query.mdx
  pages/zh-cn/components/grid.mdx
  pages/zh-cn/components/use-media-query.mdx
Labels: type: documentation

#486 fix: fix the invalid vertical-align
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/__snapshots__/password.test.tsx.snap
  components/input/input-icon.tsx
  components/table/__tests__/__snapshots__/index.test.tsx.snap
  components/table/table-head.tsx
  components/toggle/__tests__/__snapshots__/index.test.tsx.snap
  components/toggle/toggle.tsx
Labels: bug

#492 chore: add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: type: chore

#498 fix(auto-complete): fix the type constraint error in options
  .nowignore
  .vercelignore
  components/auto-complete/auto-complete.tsx
Labels: bug
