Repository geist-org/geist-ui, pull requests merged in 2021-05, with the labels that each got.

#532 fix(modal): disable backdrop even if actions missing
  components/modal/__tests__/index.test.tsx
  components/modal/modal.tsx
Labels: bug

#533 fix: upgrade to be compatible with React-17's event system
  components/use-click-away/use-click-away.ts
Labels: bug

#541 feat: useKeyboard hooks
  components/index.ts
  components/use-keyboard/__tests__/keyboard.test.tsx
  components/use-keyboard/codes.ts
  components/use-keyboard/helper.ts
  components/use-keyboard/index.ts
  components/use-keyboard/use-keyboard.ts
  components/utils/collections.ts
  components/utils/use-ssr.ts
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/use-keyboard.mdx
  pages/zh-cn/components/use-keyboard.mdx
Labels: type: feature

#542 feat(auto-complete): add forwardRef for input element
  components/auto-complete/__tests__/__snapshots__/index.test.tsx.snap
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/auto-complete.tsx
  pages/en-us/components/auto-complete.mdx
  pages/zh-cn/components/auto-complete.mdx
Labels: type: feature

#546 fix(auto-complete): fix size of loading icon
  components/auto-complete/auto-complete.tsx
Labels: bug

#547 fix(auto-complete): hide shadow when no content
  components/auto-complete/auto-complete-dropdown.tsx
Labels: bug

#548 docs: fix display & badge spacing
  pages/en-us/components/badge.mdx
  pages/en-us/components/display.mdx
  pages/zh-cn/components/badge.mdx
  pages/zh-cn/components/display.mdx
Labels: type: documentation
