Repository geist-org/geist-ui, pull requests merged in 2022-02, with the labels that each got.

#696 feat(tabs): display highlight on tabs when mouse-in
  .jest.config.js
  components/index.ts
  components/shared/dropdown.tsx
  components/shared/highlight.tsx
  components/table/__tests__/index.test.tsx
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  components/themes/themes.ts
  components/use-classes/__tests__/index.test.tsx
  components/use-classes/index.ts
  components/use-classes/use-classes.ts
  components/utils/collections.ts
  components/utils/layouts.ts
  components/utils/use-previous.ts
  pages/en-us/components/tabs.mdx
  pages/zh-cn/components/tabs.mdx
Labels: type: feature

#697 fix(styles): optimize font-size for code block
  components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
  components/css-baseline/css-baseline.tsx
Labels: type: styles

#699 docs: redesign documentation styles
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs-item.tsx
  lib/components/attributes/attributes-table.tsx
  lib/components/attributes/attributes-title.tsx
  lib/components/layout/menu/menu-sticker.tsx
  lib/components/mdx-widgets/colors/index.tsx
  lib/components/mdx-widgets/hybrid-code.tsx
  lib/components/mdx-widgets/index.ts
  pages/_app.tsx
  pages/en-us/components/text.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/scale.mdx
  pages/en-us/guide/server-render.mdx
  pages/en-us/guide/themes.mdx
  pages/zh-cn/components/text.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/guide/scale.mdx
  pages/zh-cn/guide/server-render.mdx
  pages/zh-cn/guide/themes.mdx
Labels: type: documentation

#700 docs: customize separate styles for instalation page
  lib/components/layout/layout.tsx
  pages/en-us/guide/installation.mdx
  pages/zh-cn/guide/installation.mdx
Labels: type: documentation

#703 fix(links): keep links consistent across typography
  components/image/__tests__/__snapshots__/browser.test.tsx.snap
  components/link/__tests__/__snapshots__/index.test.tsx.snap
  components/link/icon.tsx
  components/link/link.tsx
  lib/components/mdx-widgets/hybrid-link.tsx
  pages/en-us/guide/themes.mdx
Labels: type: bug

#704 feat(button): slightly reduce the default width
  components/button/__tests__/__snapshots__/icon.test.tsx.snap
  components/button/button.tsx
  components/modal/__tests__/__snapshots__/index.test.tsx.snap
Labels: type: feature

#706 docs: optimize the determination and rendering of relative url
  lib/components/mdx-widgets/hybrid-link.tsx
Labels: type: documentation

#707 docs: fix tabs layout of install page
  pages/en-us/guide/installation.mdx
  pages/zh-cn/guide/installation.mdx
Labels: type: documentation

#708 feat(toast): redesign hooks to compatible with placement and styles
  components/geist-provider/geist-provider.tsx
  components/index.ts
  components/snippet/snippet.tsx
  components/use-toasts/__tests__/__snapshots__/index.test.tsx.snap
  components/use-toasts/__tests__/index.test.tsx
  components/use-toasts/helpers.tsx
  components/use-toasts/index.ts
  components/use-toasts/toast-container.tsx
  components/use-toasts/toast-item.tsx
  components/use-toasts/use-toast.tsx
  components/utils/use-geist-ui-context.ts
  lib/components/customization/codes.tsx
  lib/components/mdx-widgets/colors/index.tsx
  lib/components/playground/editor.tsx
  pages/en-us/components/file-tree.mdx
  pages/en-us/hooks/use-clipboard.mdx
  pages/en-us/hooks/use-toast.mdx
  pages/zh-cn/components/file-tree.mdx
  pages/zh-cn/hooks/use-clipboard.mdx
  pages/zh-cn/hooks/use-toast.mdx
Labels: type: feature, type: refactor

#710 feat(tabs): allow to hide the border when tab is activated
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/__tests__/index.test.tsx
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  lib/components/layout/layout.tsx
  lib/components/layout/menu/menu-sticker.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  pages/en-us/components/input.mdx
  pages/en-us/components/modal.mdx
  pages/en-us/components/select.mdx
  pages/en-us/components/tabs.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/hooks/use-classes.mdx
  pages/en-us/hooks/use-input.mdx
  pages/en-us/hooks/use-modal.mdx
  pages/en-us/hooks/use-tabs.mdx
  pages/zh-cn/components/input.mdx
  pages/zh-cn/components/modal.mdx
  pages/zh-cn/components/select.mdx
  pages/zh-cn/components/tabs.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/hooks/use-classes.mdx
  pages/zh-cn/hooks/use-input.mdx
  pages/zh-cn/hooks/use-modal.mdx
  pages/zh-cn/hooks/use-tabs.mdx
Labels: type: feature

#711 chore: release v2.3.0-rc.1
  package.json
Labels: type: chore

#712 docs: add global search and text indexing
  .github/CONTRIBUTING.md
  components/shared/highlight.tsx
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/use-keyboard/use-keyboard.ts
  components/utils/layouts.ts
  lib/components/index.ts
  lib/components/layout/layout.tsx
  lib/components/layout/sidebar/index.tsx
  lib/components/pures/controls.tsx
  lib/components/search/helper.ts
  lib/components/search/index.tsx
  lib/components/search/search-icon.tsx
  lib/components/search/search-item.tsx
  lib/components/search/search-items.tsx
  lib/components/search/search-right-label.tsx
  lib/components/search/search.tsx
  lib/data/seeds-en-us.json
  lib/data/seeds-zh-cn.json
  lib/data/seeds.ts
  package.json
  pages/_app.tsx
  scripts/seeds/codesandbox.json
  scripts/seeds/links.json
  scripts/seeds/presets.js
  scripts/seeds/update.js
Labels: type: documentation

#714 chore: release v2.3.0
  components/geist-provider/geist-provider.tsx
  components/use-toasts/use-toast.tsx
  components/utils/use-geist-ui-context.ts
  package.json
Labels: type: chore

#716 docs: redesign search menu
  lib/components/search/helper.ts
  lib/components/search/search-item.tsx
  lib/components/search/search-items.tsx
  lib/components/search/search-right-label.tsx
  lib/components/search/search.tsx
Labels: type: documentation

#719 docs: add powered-by for vercel sponsor
  README.md
  lib/components/layout/layout.tsx
  lib/components/layout/powered-by.tsx
  pages/en-us/guide/introduction.mdx
  pages/zh-cn/guide/introduction.mdx
Labels: type: documentation

#720 fix(use-click-away): update handler reference
  components/use-click-away/__tests__/click-away.test.tsx
  components/use-click-away/use-click-away.ts
  pages/en-us/hooks/use-click-away.mdx
  pages/zh-cn/hooks/use-click-away.mdx
Labels: type: bug

#721 chore: remove powered-by banner
  README.md
  lib/components/layout/layout.tsx
  lib/components/layout/powered-by.tsx
Labels: type: documentation

#723 docs: redesign menu
  lib/components/layout/index.tsx
  lib/components/layout/layout.tsx
  lib/components/layout/menu/index.tsx
  lib/components/layout/menu/menu-links.tsx
  lib/components/layout/menu/menu-mobile.tsx
  lib/components/layout/menu/menu-sticker.tsx
  lib/components/layout/sidebar/active-catalog.tsx
  lib/components/layout/sidebar/active-link.tsx
  lib/components/layout/sidebar/index.tsx
  lib/components/layout/sidebar/side-item.tsx
  lib/components/layout/sidebar/tabbar-mobile.tsx
  lib/components/pures/controls.tsx
  lib/config-context.ts
  lib/config-provider.tsx
  pages/_app.tsx
  pages/en-us/index.tsx
  pages/zh-cn/index.tsx
Labels: type: documentation

#728 docs: dynanic load components to improve first screen render
  .gitignore
  lib/components/layout/layout.tsx
  lib/components/layout/menu/index.tsx
  lib/components/layout/menu/menu-skeleton.tsx
  lib/components/layout/menu/menu.tsx
  lib/components/layout/powered-by/index.ts
  lib/components/layout/powered-by/powered-by.tsx
  lib/components/layout/sidebar/index.tsx
  lib/components/layout/sidebar/sidebar-skeleton.tsx
  lib/components/layout/sidebar/sidebar.tsx
  lib/components/mdx-widgets/icons-gallery/icons-gallery.tsx
  lib/components/mdx-widgets/icons-gallery/index.tsx
  lib/data/seeds-zh-cn.json
  next.config.js
  package.json
  pages/_app.tsx
  scripts/rollup.config.js
  scripts/side-effects.js
  yarn.lock
Labels: type: documentation

#729 fix: ensure tabs can update handlers when language changes
  lib/components/layout/menu/menu.tsx
Labels: type: documentation

#727 fix(input): remove fixed height of label container
  components/auto-complete/__tests__/__snapshots__/search.test.tsx.snap
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/input/__tests__/__snapshots__/password.test.tsx.snap
  components/input/input.tsx
Labels: type: bug

#730 docs: set side-effects when build document site
  scripts/side-effects.js
Labels: type: documentation

#732 fix(password): pass all scale props for internally wrapped components
  components/index.ts
  components/input/__tests__/password.test.tsx
  components/input/password.tsx
  components/use-scale/__tests__/scale.test.tsx
  components/use-scale/scale-context.ts
  components/use-scale/utils.ts
  components/use-scale/with-scale.tsx
Labels: type: bug

#733 chore: release v2.3.1
  package.json
Labels: type: chore

#738 feat: support for render styles to html on the server side
  .gitignore
  components/css-baseline/css-baseline.tsx
  examples/remix/README.md
  examples/remix/api/index.js
  examples/remix/app/entry.client.tsx
  examples/remix/app/entry.server.tsx
  examples/remix/app/root.tsx
  examples/remix/app/routes/index.tsx
  examples/remix/package.json
  examples/remix/public/favicon.ico
  examples/remix/remix.config.js
  examples/remix/remix.env.d.ts
  examples/remix/tsconfig.json
  examples/remix/vercel.json
  package.json
  scripts/built-in/styled-jsx-server.es.js
Labels: type: feature

#742 fix(button-dropdown): remove the default style and side effects under webkit
  components/button-dropdown/__tests__/__snapshots__/index.test.tsx.snap
  components/button-dropdown/button-dropdown.tsx
  components/css-baseline/__tests__/__snapshots__/baseline.test.tsx.snap
  components/css-baseline/css-baseline.tsx
  package.json
Labels: type: bug

#745 docs: fix height of search-box on firefox browser
  lib/components/search/search.tsx
Labels: type: documentation
