Repository geist-org/geist-ui, pull requests merged in 2022-01, with the labels that each got.

#658 feature Update tabs-item.tsx
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs-context.ts
  components/tabs/tabs-item.tsx
  components/tabs/tabs.tsx
  pages/en-us/components/tabs.mdx
  pages/zh-cn/components/tabs.mdx
Labels: type: feature

#655 fix(select): option horizontal overflow
  components/select/select-option.tsx
Labels: bug

#652 chore: update create-next-app example to Nextjs 12
  examples/create-next-app/next-env.d.ts
  examples/create-next-app/package.json
Labels: type: chore

#612 fix: components' `displayName` typos
  components/select/select-input.tsx
  components/table/table-column.tsx
  components/tabs/tabs-item.tsx
  components/tooltip/tooltip.tsx
  components/tree/tree-folder-icon.tsx
Labels: bug

#633 fix: Removed unnecessary code in Grid Component
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/basic-item.tsx
  components/select/__tests__/__snapshots__/multiple.test.tsx.snap
Labels: bug

#665 chore: upgrade dependency to be compatible with next 12
  .gitignore
  components/grid/grid-container.tsx
  components/grid/grid.tsx
  components/index.ts
  components/themes/themes.ts
  components/utils/types.ts
  lib/components/menu/menu-links.tsx
  lib/config-context.ts
  lib/config-provider.tsx
  next-env.d.ts
  next.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: type: chore

#632 chore: update installation.mdx
  pages/en-us/guide/installation.mdx
Labels: type: chore

#667 chore: release v2.2.1
  package.json
  yarn.lock
Labels: type: chore

#668 build: bundle all components with rollup instead of webpack
  package.json
  scripts/fix-styled-jsx.js
  scripts/rollup.config.js
  yarn.lock
Labels: type: bug, type: dependencies

#669 chore: release v2.2.2
  package.json
Labels: type: chore

#670 chore: update nextjs example
  examples/create-next-app/.eslintrc.json
  examples/create-next-app/next-env.d.ts
  examples/create-next-app/next.config.js
  examples/create-next-app/package.json
  examples/create-next-app/pages/index.tsx
  examples/create-next-app/tsconfig.json
Labels: type: chore

#674 fix: fix reference paths after type compilation
  package.json
  scripts/tsconfig.json
Labels: type: bug

#675 chore: release v2.2.3
  package.json
Labels: type: chore

#672 fix: Add alt text for image to avoid eslint warn
  examples/create-next-app/pages/index.tsx
Labels: type: chore

#678 chore: rename the GH repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  components/input/__tests__/index.test.tsx
  examples/create-next-app/pages/index.tsx
  examples/custom-themes/src/theme.js
  lib/components/header.tsx
  lib/constants.ts
  package.json
  pages/_app.tsx
  pages/en-us/components/badge.mdx
  pages/en-us/components/card.mdx
  pages/en-us/components/tabs.mdx
  pages/en-us/guide/installation.mdx
  pages/en-us/guide/introduction.mdx
  pages/en-us/guide/themes.mdx
  pages/en-us/index.tsx
  pages/zh-cn/components/badge.mdx
  pages/zh-cn/components/card.mdx
  pages/zh-cn/components/tabs.mdx
  pages/zh-cn/guide/installation.mdx
  pages/zh-cn/guide/introduction.mdx
  pages/zh-cn/guide/themes.mdx
  pages/zh-cn/index.tsx
Labels: type: chore

#681 build: manually add references to styled-jsx for rollup ecosystem
  .gitignore
  package.json
  scripts/babel.config.js
  scripts/built-in/styled-jsx-server.es.js
  scripts/built-in/styled-jsx.cjs.js
  scripts/built-in/styled-jsx.es.js
  scripts/fix-styled-jsx.js
  scripts/move-built-in.js
  scripts/rollup.config.js
  yarn.lock
Labels: type: bug, type: chore

#682 chore: append redirects for project renaming
  next.config.js
Labels: type: chore

#683 chore: simplify the type srouce of third-party lib
  components/css-baseline/css-baseline.tsx
  package.json
  typings/styled.d.ts
Labels: type: chore, type: dependencies

#685 feat: add scale to password component
  components/input/password.tsx
  pages/en-us/components/button-dropdown.mdx
  pages/zh-cn/components/button-dropdown.mdx
Labels: type: feature

#686 fix(tabs): fix type of left-space to match component input
  components/tabs/tabs-context.ts
  components/tabs/tabs.tsx
  lib/components/menu/menu-sticker.tsx
Labels: type: bug

#687 feat(page): add props to control the style of dot
  components/page/__tests__/__snapshots__/index.test.tsx.snap
  components/page/__tests__/index.test.tsx
  components/page/page.tsx
  pages/en-us/components/page.mdx
  pages/zh-cn/components/page.mdx
Labels: type: feature

#688 docs: remove customization tab
  lib/components/controls.tsx
  lib/components/customization/colors.tsx
  lib/components/customization/demo.tsx
  lib/components/customization/editor.tsx
  lib/components/displays/home-cell.tsx
  lib/data/metadata-en-us.json
  lib/data/metadata-zh-cn.json
  next.config.js
  pages/en-us/customization/index.tsx
  pages/en-us/index.tsx
  pages/zh-cn/customization/index.tsx
  pages/zh-cn/index.tsx
Labels: type: documentation

#692 feat(image): allow component to render svg string
  components/image/__tests__/__snapshots__/browser.test.tsx.snap
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/index.test.tsx
  components/image/helpers.ts
  components/image/image-browser.tsx
  components/image/image.tsx
  pages/en-us/components/image.mdx
  pages/zh-cn/components/image.mdx
  public/images/branch-domains.png
  public/images/custom-domains.png
  public/images/geist-banner-dark.png
  public/images/geist-banner-text.png
  public/images/zeit-react-logo.png
Labels: type: feature

#694 fix(tabs): fix sub-components ignore theme changes
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/tabs-item.tsx
Labels: type: bug

#695 docs: fix the layout of the document site
  lib/components/layout/layout.tsx
  lib/components/layout/menu/menu-links.tsx
  lib/components/pures/controls.tsx
  pages/_app.tsx
Labels: type: documentation
